### ISSUE TITLE
Book Prievew

### ISSUE THREAD

**Issue by Dogs777** [ezfe/tellraw#102]
I was setting up a warp book for my realms world and i realized that the book preview function isn't working properly. can you fix it, the prievew appeared as it was on the next line when in minecraft it appeared on the same line as the previous text

**Comment by ezfe** [comment]
I am aware of this issue, however it's low on my to-do list. Because you can change the font size (see settings page), I cannot completely resolve this unless I choose to override the font size. Also, it requires a lot of work finely tuning widths and heights.

**Comment by ezfe** [comment]
I'm closing this issue and won't be immediately looking to correct it. Book previews are a minefield of issues, to say the least, and it's extremely complicated to replicate Minecraft's book layout in the browser.
