### ISSUE TITLE
Phrase

### ISSUE THREAD

**Issue by Dogstalotl** [ezfe/tellraw#103]
Whenever i add a new phrase to a book, my phrase disappears while the code is still in the code

**Comment by ezfe** [comment]
Can you add a screenshot

**Comment by TheMaxShaft** [comment]
![screen shot 2015-01-21 at 10 01 58 pm](https://cloud.githubusercontent.com/assets/10644674/5849843/2e731d14-a1b9-11e4-96b5-4121290feb19.png)
as you see the code with the text is there while the text isn't

**Comment by TheMaxShaft** [comment]
The Code (Highlighted) Is there while the text isn't
![screen shot 2015-01-21 at 10 05 55 pm](https://cloud.githubusercontent.com/assets/10644674/5849884/bd603b74-a1b9-11e4-928c-f0c0f6cf8ab5.png)

**Comment by ezfe** [comment]
Is this still an issue? If so can you explain how you get it to occur

**Comment by TheMaxShaft** [comment]
my theory is that it is out of an invisible "Box" and since it is going over the border, when it is updated (by going to add or edit a thing) it checks if it is going out of the border and it will remove what is going out of it. If it doesn't work, try it with quotes, numbers and stuff.

**Comment by ezfe** [comment]
LOL so quotes aren't being inserted into the text fields properly.

**Comment by ezfe** [comment]
This should be fixed, let me know if it isn't
