### ISSUE TITLE
Problem Adding Multiple Pages

### ISSUE THREAD

**Issue by ETBCOR** [ezfe/tellraw#109]
Hey ezfe! (By the way, I also tweeted you.) Love your tellraw generator tool, and I use it all the time. I am currently in book mode, and have exceeded the amount of text that can be displayed on one page, and don't quit get how to split it into more pages. Any help would be appreciated, thanks, Ethan. Also, to contact me, you can either email me here: ETBCOR@gmail.com or tweet me @ETBCOR

**Comment by ezfe** [comment]
Hmm, I sent you a tweet, let me know if you need more help.
