### ISSUE TITLE
"/give witten_book ..." problem

### ISSUE THREAD

**Issue by Andre424971** [ezfe/tellraw#110]
when I make a written book with the generateor, and run the command, the format of the text (Color, Font, ...) will be not used.

Can you fix that?

And sorry, if my english is bad... I'm from switzerland

#EDIT

The Problem is: Hover text are not supportet or in the wrong format...

**Comment by ezfe** [comment]
So, to clarify, you're making a book, and the issue is with the text that appears inside the box when you hover?
