### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by Duncan3242** [ezfe/tellraw#111]
Hi, I recently tried to save one of my awesomely generated commands, but when I save it, it just does not work, it does not appear in the list when I press "OK", when I reload, or do anything. I am just going to keep the command in a document for now and import it when I need, but I would have really liked that feature if it works. But if everyone else finds that it works, then don't go to the trouble of fixing it for me.

**Comment by ezfe** [comment]
I'll do a quick test of the saves feature to make sure it's working.

Do not rely on saves, they aren't particularly reliable, as they reset with your cookies. Also sometimes I need to force-reset the entire website so you may loose your saves. I recommend saving things either in a command block (paste the exported item into the command block, and copy it out when you need to re-import it) or in a text document like you said.

**Comment by ezfe** [comment]
Yeah, seems to work fine here. If you can, make a screen recording. On a mac, quicktime has this feature in the `File` menu

**Comment by jshggagnier** [comment]
I have the exact same problem
I saved my file but it wont show up
please tell me how to fix it i spent alot of time on the command
It is in the cookies folder but wont show up (windows 7, chrome)

**Comment by ezfe** [comment]
@jshggagnier When you say that "it is in the cookies folder," do you mean that you can see the save itself, or just that I'm storing cookies?

If you can see the save itself, but its not showing up, get the contents of the cookie and put it here.
