### ISSUE TITLE
Character Limit issue for tellraw generator! (Minecraft)

### ISSUE THREAD

**Issue by DarkFlareMC707** [ezfe/tellraw#113]
I'm generation a command that gives me a book with commands I have chosen in it for many pages (A.K.A. my "control book" for commands) and I just wanted a tellraw command to give it to the player that clicks it! This works fine but there is one issue... Only 90 charactes is REALLY small because this book only doing a /give command is allready over 3000 characters so I have a huge issue. Please let there be more characters for you JSON tellraw generator! Your my only source! For the Provided data below shows my smallest "control book." It Doesn't all fit!

Sincerely,
Isaak Nijakowski

 Provided Data - Do not modify below this line

```
/tellraw @p ["",{"text":"Give Control Book","color":"green","bold":"true","italic":"true","underlined":"true","clickEvent":{"action":"run_command","value":"/give DarkFlareMC707 minecraft:written_book 1 0 {display:{Name:Control Book,Lore:[The book to control the game!]},title:\"[Control Book]\",author:\"Isaak N.\",generation:0,pages:[\"{text:\\\"[Command Block]\\\",color:yellow,bold:true,italic:true,hoverEvent:{action:'show_text',value:\\\"Give yourself a command block\\\"},clickEvent:{action:'run_command',value:\\\"/give @p minecraft:command_block\\\"},extra:[{text:\\\"[Spawnpoint]\\\",color:gold,bold:true,italic:false,hoverEvent:{action:'show_text',value:\\\"Set spawnpoint\\\"},clickEvent:{action:'run_command',value:\\\"/spawnpoint\\\"}}]}\"]}"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"A control book to run the game!","color":"gray"}]}}}]
```

**Comment by ezfe** [comment]
The limit is not set by me. You can use /trigger to make a command block run the command.
