### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Marcono1234** [ezfe/tellraw#115]
1. When you select for the `hoverEvent` `Show Text` and select a color and add the text and delete everything, it will say the next time you want to add this `hoverEvent` that your selected color is `None` but the preview field has still the last color you selected.

2. When you click report issue and cancel this while you edited some text, the window has closed. But when you press `Add Text +` then, it will show the window with the last edited text.

3. When you click on something with a `hoverEvent` in the preview, it only shows `show_text:[object Object]` as text instead of the actual text

**Comment by ezfe** [comment]
1. Fixed 279e0fe16c4629e92126b3035b831727e9890bba

2. Working as Intended

3. Eh. Yeah I know I need to fix that.
