### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by randomdude999** [ezfe/tellraw#116]
I press 'Save current string' and enter a name. Then it cancels no matter what button I press.

**Comment by randomdude999** [comment]
Looked up the previous issues. I checked both the cookies and local storage and still nothing. (Local storage contains the command but under a generic name 'jobject')

**Comment by ezfe** [comment]
Is it possible for you to take a screen recording?

**Comment by randomdude999** [comment]
Sure. ~~Here it is.~~ Waiting for it to upload to Drive... 254 MB an it's about 50 seconds...
