### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by KleinerGitHub** [ezfe/tellraw#117]
Please enter steps to reproduce the issue below, as well as any other information you want to include

Short Description:
"<Text>" was not Display in preview but it works on server ;)
I use Firefox version: 37.0.2

//edit ok, the same issue at GitHub :P   < T e x t > were hidden
[{"text":"Chat\\n","color":"dark_red"},{"text":"!< T e x t > ","color":"aqua","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"!Wilkommen auf dem Server","color":"dark_purple"}]}}}]

 Provided Data - Do not modify below this line

```
[{"text":"Chat\\n","color":"dark_red"},{"text":"!<Text> ","color":"aqua","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"!Wilkommen auf dem Server","color":"dark_purple"}]}}}]
```

**Comment by ezfe** [comment]
#40
