### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Znacor** [ezfe/tellraw#118]
Please enter steps to reproduce the issue below, as well as any other information you want to include

The arrows are not propirly added to your generator, they are way smaller ingame and they display way of were they shoud display.

 Provided Data - Do not modify below this line

```
[{"text":"    Welcome to","bold":"true"},{"text":"\\n   ➳ Infinitri ➳","bold":"true"},{"text":"\\nCompetetive Bowgame","color":"dark_gray"},{"text":"\\n          ► ▼ ◄"},{"text":"\\nThis book will teach you how to play the different gamemodes and how to moderate using the game settings.","color":"black"},{"text":"\\n"},{"text":"\\nSkip the Page ","color":"red"},{"text":"to get started","color":"black"},{"text":" ➟ ","color":"black"}]
```

**Comment by ezfe** [comment]
If you type them in game do they display the way you want them to show?

**Comment by Znacor** [comment]
In game the icons are much smaller than if you were to type them on the website

**Comment by ezfe** [comment]
Can you show me a screenshot?
