### ISSUE TITLE
Book output

### ISSUE THREAD

**Issue by Mwthorn** [ezfe/tellraw#120]
I am impressed with the output screen. But there is a small problem that it seems to skip to the next line . Well... these two screenshots should say the differences.
Here is how it looks on the generator:
![screenshot_3](https://cloud.githubusercontent.com/assets/8504075/7444728/d7abfc8e-f191-11e4-8077-6cc25af572ed.png)
And here is how it looks in-game with the command:
![screenshot_1](https://cloud.githubusercontent.com/assets/8504075/7444727/d5113df4-f191-11e4-9e09-259e15696d9c.png)
Not a big deal, but it would be nice if that was fixed :+1:

**Comment by ezfe** [comment]
#102
