### ISSUE TITLE
View For Books

### ISSUE THREAD

**Issue by CamoJackson** [ezfe/tellraw#121]
The text for the book dose not match the formatting of minecraft

**Comment by CamoJackson** [comment]
![javaw 2015-05-03 16-51-59-33](https://cloud.githubusercontent.com/assets/11304426/7446869/ca6db760-f1b4-11e4-9eb8-9dc0681c6ba6.jpg)
![mcjson book problem](https://cloud.githubusercontent.com/assets/11304426/7446876/2f2086b0-f1b5-11e4-8c49-761f770e4921.PNG)

**Comment by ezfe** [comment]
#102
