### ISSUE TITLE
Importing json results in "Object Verification Failed"

### ISSUE THREAD

**Issue by Voltasalt** [ezfe/tellraw#123]
The JSON I used:

    ["",{"text":"--- ","color":"red"},{"text":"Handbook: Teleportation","color":"green"},{"text":" ---\n","color":"red"},{"text":"/tpa <name>","color":"red"},{"text":" - Sends a teleport request to a player\n","color":"green"},{"text":"/tpaccept","color":"red"},{"text":" - Accepts a teleport request from another player\n","color":"green"},{"text":"/tpdeny","color":"red"},{"text":" - Declines a teleport request from another player\n","color":"green"},{"text":"/warp","color":"red"},{"text":" - Shows you a list of warps (with more clicky goodness)\n","color":"green"},{"text":"/spawn","color":"red"},{"text":" - Teleports you to the server's spawn point","color":"green"}]

**Comment by ezfe** [comment]
You can't import the output JSON, you can only import the exported JSON.

Import this instead:

```json
{"command":"/tellraw @p %s","jobject":[{"text":"--- ","color":"red"},{"text":"Handbook: Teleportation","color":"green"},{"text":" ---\n","color":"red"},{"text":"/tpa <name>","color":"red"},{"text":" - Sends a teleport request to a player\n","color":"green"},{"text":"/tpaccept","color":"red"},{"text":" - Accepts a teleport request from another player\n","color":"green"},{"text":"/tpdeny","color":"red"},{"text":" - Declines a teleport request from another player\n","color":"green"},{"text":"/warp","color":"red"},{"text":" - Shows you a list of warps (with more clicky goodness)\n","color":"green"},{"text":"/spawn","color":"red"},{"text":" - Teleports you to the server's spawn point","color":"green"}],"jtemplate":"tellraw"}
```
