### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NateTDOM** [ezfe/tellraw#124]
The command i am given is literally not working. No other explanation than that just not even working. /tellraw @a ["",{"text":"Hey there, thank you so much for playing my map. As my treat i will let you search around the redstone of the map if you wanna.","clickEvent":{"action":"run_command","value":""},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[]}}},{"text":" Creative","color":"red","clickEvent":{"action":"run_command","value":"/gamemode 1"}},{"text":" Spectator","color":"green","clickEvent":{"action":"run_command","value":"/gamemode 3"}}]

**Comment by ezfe** [comment]
Please use the export button and paste the text it gives you here
