### ISSUE TITLE
Book Page Turning

### ISSUE THREAD

**Issue by RicoPeav** [ezfe/tellraw#125]
When I am making a book it won't let me turn the page, so I just stop. Can someone please help.

**Comment by ezfe** [comment]
I'm confused what you mean? Have you tried clicking add > new book page > add?

**Comment by RicoPeav** [comment]
I will try right now

**Comment by RicoPeav** [comment]
I can't find "add"

**Comment by ezfe** [comment]
"Add Text" big blue button. Then choose "Book Page / Sign Line" at the top
