### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Redstonegenie7** [ezfe/tellraw#126]
Please enter steps to reproduce the issue below, as well as any other information you want to include
The problom is when i put it in a command block it comes out as "KitchenOffice"
instead of "
Kitchen
Office"

 Provided Data - Do not modify below this line

```
[{"text":"Kitchen","color":"gold","clickEvent":{"action":"run_command","value":"/setblock -28 5 25 redstone_block"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Go To Kitchen"}]}}},{"text":"Office","color":"gold","clickEvent":{"action":"run_command","value":"/tp @p -42 30 1"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Go To The Office"}]}}}]
```

**Comment by ezfe** [comment]
Are you using \n to create your newlines/linebreaks?
