### ISSUE TITLE
Issue Report - Translation Issue (ko)

### ISSUE THREAD

**Issue by Devonnuri** [ezfe/tellraw#128]
Please enter steps to reproduce the issue below, as well as any other information you want to include

점수오브젝트 to 스코어보드

 Provided Data - Do not modify below this line

```
[{"text":"북\\n"}]
```

**Comment by ezfe** [comment]
Fixed in de31f63061d9985b32b21f3073a36a0b4c46b4e2

Please check that I have fixed it properly.
