### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Baron-Sengir** [ezfe/tellraw#129]
Please enter steps to reproduce the issue below, as well as any other information you want to include

I make the command, I preview the command (Oh hey! My lines are sorted already!). I run the command, the lines are not separate.

E.G. Preview: Hi
                       This is a book!
                       No duh Sherlock!

Actually:          HiThis is a book!No duh Sherlock!

 Provided Data - Do not modify below this line

```
[{"text":"Page two: Gamemodes"},{"text":"Page 3: Gamerules"},{"text":"Page 4: Kills"},{"text":"Page 5: Trolls"},{"text":"Page 6: Trolls"},{"text":"Page 7: Mobs"},{"text":"Page 8: Weather"},{"text":"Page 9: Gives"}]
```

**Comment by Baron-Sengir** [comment]
It would be nice if you made each "add text" a new line, maybe a toggleable feature.  Also please make longer commands in the book possible.

**Comment by ezfe** [comment]
I'm not going to do that because each Add Text has different formatting. If you want different formatting on the same line, you'd be out of luck. I have a new version of the generator that I'm working on that will resolve these issues.

Until then, type \n to make a new line.
