### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by federico2407** [ezfe/tellraw#130]
the @p don't work how i can make it?
[{"text":"Benvenuto ","color":"dark_blue","bold":"true"},{"text":"@p ","color":"yellow","bold":"true"},{"text":"su ","color":"dark_blue","bold":"true"},{"text":"Diamond","color":"aqua","bold":"true"},{"text":"War","color":"red","bold":"true"}]
```

**Comment by ezfe** [comment]
When you click "Add Text", click the "Selector" format.
