### ISSUE TITLE
Issue Report - Translation Issue (ko)

### ISSUE THREAD

**Issue by Devonnuri** [ezfe/tellraw#132]
Please enter steps to reproduce the issue below, as well as any other information you want to include

언제든지 다시 설정하고 브라우저 쿠키에 따라 달라질 수 있습니다 저장합니다. 오랜 기간 동안 그들에 의존하지 마십시오.

->

브라우저 쿠키에 따라 커맨드가 사라질수 있습니다. 오랫동안 이 기능에 의존하지 마십시오.

 Provided Data - Do not modify below this line

```
[{"text":"dd"}]
```

**Comment by ezfe** [comment]
done, will publish eventually
