### ISSUE TITLE
1.9 not supported

### ISSUE THREAD

**Issue by Tallone55** [ezfe/tellraw#140]
While the generator works near-flawlessly in 1.8, the strict JSON parsing introduced in the 1.9 snapshots means that no JSON currently created in the generator will work in 1.9, However strict JSON is supported in 1.8. Thus, I suggest updating your generator so that it will be compatible with 1.9, while remaining compatible with 1.8.

**Comment by ezfe** [comment]
The commands generated by my project are fully compatible with 1.9
