### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by LearnTP** [ezfe/tellraw#144]
Please enter steps to reproduce the issue below, as well as any other information you want to include
Book Generator:

Line One: ```Hello``` / Colour: ```dark_aqua```
Line Two:  ```This is an example text``` / Colour: ```none```

Issue: the words ```Hello this is an``` appear in ```dark_aqua```, with only ```example text``` being left as ```none```

Screenshot: [here](https://gyazo.com/0724f52a07c75c40bfb9783bdf2e152f)
Command Copied Directly from Commandblock: 
```/give @p written_book 1 0 {pages:["[\"\",{\"text\":\"Hello\",\"color\":\"dark_aqua\"},{\"text\":\" this is an example text\",\"color\":\"none\"}]"],title:Book,author:TellrawGenerator}```

Thanks,
Ollie.

 Provided Data - Do not modify below this line

```
[{"text":"Hello","color":"dark_aqua"},{"text":" this is an example text"}]
```

**Comment by ezfe** [comment]
This is due to a bug with Minecraft where one line cannot seem to have multiple styles.

Type \n right before "this" to insert a line break and it should work properly.
