### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by dejaeva** [ezfe/tellraw#146]
Not Much Of An Issue, But Why Only 1 Page On The Books? Plss Fix! If You Do, it Would Be My Number One Fav Website! I Dont Car How Long It Will Take, I Would Wait 1 Year If I Must! Mabey Longer! 

Sorry For Spelling Mistakes... 

PLEASE FIX!!!

**Comment by ezfe** [comment]
There's a button to add a new book page when you click Add Text
