### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Steev93** [ezfe/tellraw#147]
Please enter steps to reproduce the issue below, as well as any other information you want to include

In console; Error given: "Please don't use special characters."

 Provided Data - Do not modify below this line

```
[{"text":"Welcome to Sky Servers Skyblock","color":"dark_blue","bold":true,"italic":true},{"selector":"www.skyservers.net/eranks","clickEvent":{"action":"open_url","value":"www.skyservers.net/eranks"}},{"text":"This is the Guidebook for you donating. This explains what Ranks and Perks you have you have access to"}]
```

**Comment by ezfe** [comment]
Well you typed something it didn't like. What were you trying to add when you get this error.
