### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by HenrikoMagnifico** [ezfe/tellraw#148]
Please enter steps to reproduce the issue below, as well as any other information you want to include

Output format doesn't work as of the newest Minecraft 1.9 update snapshots, the new format uses strict JSON and the old generator format isn't supported anymore.

 Provided Data - Do not modify below this line

```
[]
```

**Comment by ezfe** [comment]
Does it actually not work? Because I haven't had it not work for me

**Comment by HenrikoMagnifico** [comment]
Never mind, close this thread. The just released snapshot fixed everything. Thanks
