### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by MCcrafter08LP** [ezfe/tellraw#149]
Can you pls make a download version of the generator ;) thanks

**Comment by ezfe** [comment]
You can download the generator by using this URL: https://github.com/ezfe/tellraw/archive/master.zip

You will have to re-download this (from the same URL) whenever I change it, however.

**Comment by MCcrafter08LP** [comment]
thx

2015-10-01 1:58 GMT+02:00 Ezekiel Elin <notifications@github.com>:

**Comment by MCcrafter08LP** [comment]
--- how i can use that?? xD

2015-10-05 14:22 GMT+02:00 MCcrafter08LP MCcrafter08LP <
mccrafter08lp@gmail.com>:

**Comment by ezfe** [comment]
Open the index.html file in your web browser
