### ISSUE TITLE
Hover Event Bug

### ISSUE THREAD

**Issue by brooky1010** [ezfe/tellraw#153]
When I click add text there isn't a box that shows up anymore.
I have to type the code myself.

**Comment by ezfe** [comment]
You mean edit text?

**Comment by brooky1010** [comment]
Yes

Op zaterdag 7 november 2015 heeft Ezekiel Elin <notifications@github.com>
het volgende geschreven:

> You mean edit text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ezfe/tellraw/issues/153#issuecomment-154742097>.
>


-- 
Verzonden via Gmail Mobile

**Comment by ezfe** [comment]
This was fixed a while back, forgot to close
