### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Andavin** [ezfe/tellraw#157]
This is an output question, but the command I made is too long to report in the URL it won't let it go through. Every time I input the command it says this:

Error: Illegal use of \": \"       Welcome to \",\"color\":\"gold\"},{\"text\":\"\n      Middle Earth\",\"color\":\"dark_purple\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/spawn\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"Brings you to Spawn\",\"color\":\"aqua\"}]}}},{\"text\":\"!\",\"color\":\"gold\"},{\"text\":\"\n\n   +-------------+\",\"color\":\"dark_gray\"},{\"text\":\"\n\n   Admin Applications\",\"color\":\"gold\"},{\"text\":\"\n      Click Here!\",\"color\":\"gray\",\"italic\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/adminapplication\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"Shows Admin Application\",\"color\":\"aqua\"}]}}},{\"text\":\"\n\n        Voting\",\"color\":\"light_purple\",\"italic\":false},{\"text\":\"\n      Click Here!\",\"color\":\"gray\",\"italic\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/votelinks\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"Shows Voting Sites\",\"color\":\"aqua\"}]}}},{\"text\":\"\n\n          \",\"color\":\"none\",\"italic\":false},{\"text\":\"->\",\"color\":\"red\",\"clickEvent\":{\"action\":\"change_page\",\"value\":\"2\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"Continue to the next page...\",\"color\":\"aqua\"}]}}}]"

This is the full command:
[Tellraw Book.txt](https://github.com/ezfe/tellraw/files/45330/Tellraw.Book.txt)

Any help is much appreciated!

**Comment by ezfe** [comment]
You mean hen you enter it in Minecraft?

**Comment by Andavin** [comment]
Yes in the console. If I put it in a command block it doesn't do anything.

**Comment by Andavin** [comment]
Okay I just tried it in Minecraft 1.8 and it worked, so I guess 1.7 is the problem. Do you know how I can make it work in 1.7.10?

**Comment by ezfe** [comment]
I don't support 1.7.10, and I don't know what the issue is. The only thing I can recommend is to start with simpler commands and figure out when it breaks.

**Comment by Andavin** [comment]
Yeah, I figured out that JSON books aren't supported in 1.7 :( 
Thank you for attempting to help anyway!
