### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Viloz** [ezfe/tellraw#158]
Please enter steps to reproduce the issue below, as well as any other information you want to include.

Step 1: Paste this command into a command block.
Step 2: Activate the command block.
Step 3: Read the book.

In the book (written in swedish, sorry) some parts of the book is colored when it shouldn't be. For example, only "Rådet" should be colored green and not "söker en". The "r" in "för" is on the wrong line as well. In the preview it looks great but ingame it is not right.

Right way:
![right_way](https://cloud.githubusercontent.com/assets/16295371/11793090/fc6482ca-a2a9-11e5-8294-dcb148879668.PNG)

Wrong way:
![wrong_way](https://cloud.githubusercontent.com/assets/16295371/11793105/0bfef486-a2aa-11e5-847c-c1ec514d3c00.PNG)

Would appreciate for this to be fixed ASAP for i am working on a custom map. Other than that, this website is awesome! Keep up the good work!

 Provided Data - Do not modify below this line

```
[{"text":"Main Story:","color":"gold","bold":true},{"text":"           "},{"text":"Rådet","color":"green","bold":true,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Ligger i berget nord-väst från hamnen."}]}}},{"text":" söker en mäktig krigare som kan ta tillbaka diamanter från den onda"},{"text":" Saunk","color":"red","bold":true,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Äventyrsmappens bov"}]}}},{"text":". Jag borde besöka "},{"text":"rådet","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Ligger i berget nord-väst från hamnen."}]}}},{"text":" för att se om jag duger."}]
```

**Comment by ezfe** [comment]
It's a minecraft bug and as far as I know there's nothing I can do about it.
