### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by DivineJr** [ezfe/tellraw#165]
Please enter steps to reproduce the issue below, as well as any other information you want to include

Don't mind the stuff below, really its this that the output image BELOW the photo is accurate, its more like a preview but who cares. It this annoys the heck out of me to see that the preview isn't accurate. It would be nice if you could fix it to be atleast more accurate.

 Provided Data - Do not modify below this line

```
[{"text":"This is the book about the Hero Nation rules, and staff."}]
```

**Comment by ezfe** [comment]
Can I see a screenshot?

**Comment by ezfe** [comment]
Are you referring to the alignment on the book?

**Comment by DivineJr** [comment]
Sorry for long wait time, and yes I mean the alignment, makes it very hard
to easily craft a book.

**Comment by ezfe** [comment]
#134
