### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by L1V1NGH311** [ezfe/tellraw#166]
Please enter steps to reproduce the issue below, as well as any other information you want to include

I have tried to create a book with your website (https://www.minecraftjson.com/) and the book had nothing but the word "null".

 Provided Data - Do not modify below this line

```
[{"text":"Who would you like to try first?"},{"text":"[Antvenom]","color":"red","clickEvent":{"action":"run_command","value":"/setblock -1208 60 -789 redstone_block 0 destroy"}}]
```

**Comment by ezfe** [comment]
This should not longer occur
