### ISSUE TITLE
Unexpected Token error

### ISSUE THREAD

**Issue by github0124** [ezfe/tellraw#168]
Please enter steps to reproduce the issue below, as well as any other information you want to include

It said Data tag parsing failed: Unexpected token 't' at: text":"click below to get holy water"},{"text":"....","obfuscated":true,"clickEvent":{"action":"run_command","value":"/give @p potion 1 8205 {CustomPotionEffects:[{Id:1,Amplifier:10,Duration:200},{Id:3,Amplifier:4,Duration:200},{Id:5,Amplifier:10,Duration:200},{Id:8,Amplifier:10,Duration:200},{Id:21,Amplifier:10,Duration:200}],display:{Name:"Holy water",Lore:["Gives you the power of god"]}}"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"srsly"}]}}}]"

```
plus i removed the \ because they weren't allowed
```
```
And this is the command /give @p written_book 1 0 {pages:["[\"\",{\"text\":\"click below to get holy water\"},{\"text\":\"....\",\"obfuscated\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/give @p potion 1 8205 {CustomPotionEffects:[{Id:1,Amplifier:10,Duration:200},{Id:3,Amplifier:4,Duration:200},{Id:5,Amplifier:10,Duration:200},{Id:8,Amplifier:10,Duration:200},{Id:21,Amplifier:10,Duration:200}],display:{Name:\\\"Holy water\\\",Lore:[\\\"Gives you the power of god\\\"]}}\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"srsly\"}]}}}]"],title:Holy Bible,author:Preist}
```

what is going on

 Provided Data - Do not modify below this line

```
[{"text":"click below to get holy water"},{"text":"....","obfuscated":true,"clickEvent":{"action":"run_command","value":"/give @p potion 1 8205 {CustomPotionEffects:[{Id:1,Amplifier:10,Duration:200},{Id:3,Amplifier:4,Duration:200},{Id:5,Amplifier:10,Duration:200},{Id:8,Amplifier:10,Duration:200},{Id:21,Amplifier:10,Duration:200}],display:{Name:\"Holy water\",Lore:[\"Gives you the power of god\"]}}"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"srsly"}]}}}]
```

**Comment by github0124** [comment]
plz help

**Comment by github0124** [comment]
```
DO IT JUST DO IT
```

**Comment by github0124** [comment]
> If its a command there is a bug

**Comment by ezfe** [comment]
This is a minecraft issue. You should have gotten a notification that looks like this:

<img width="510" alt="screen shot 2016-05-29 at 10 33 41 am" src="https://cloud.githubusercontent.com/assets/1449259/15634044/cbfdea38-2588-11e6-8f0c-b201b0133aa1.png">

I did not set that limit and cannot do anything about it.
