### ISSUE TITLE
Book "add text" doesn't have text field

### ISSUE THREAD

**Issue by primis** [ezfe/tellraw#169]
When trying to make a book in firefox on linux, you can't actually add pages to books

**Comment by ezfe** [comment]
Can you upload a screenshot for me?

**Comment by primis** [comment]
![screenshot at 2016-03-02 01 58 16](https://cloud.githubusercontent.com/assets/1566083/13452925/5bc1c158-e01a-11e5-9627-05db5131f57f.png)

**Comment by ezfe** [comment]
Yeah it's kinda weird but that's who it works. That button creates a new page for the book. You click add and it'll add it.
