### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by lennon12** [ezfe/tellraw#172]
Please enter steps to reproduce the issue below, as well as any other information you want to include

Showing items when hovering doesn't seem to work. 

 Provided Data - Do not modify below this line

```
[{"text":">Arrows<","clickEvent":{"action":"run_command","value":"/give @a arrow 64"},"hoverEvent":{"action":"show_item","value":"arrow"}}]
```

**Comment by ezfe** [comment]
This isn't actually a bug with my website, as far as I can tell everything is working properly.

You need to do {id:arrow} right now. This may change in the future to be easier.
