### ISSUE TITLE
 Object Verification Failed

### ISSUE THREAD

**Issue by BasixKOR** [ezfe/tellraw#173]
I can't import any json.

**Comment by ezfe** [comment]
Please give me an example of what you are trying to import

**Comment by BasixKOR** [comment]
`["",{"text":"Hello!"}]`
Like this.

**Comment by ezfe** [comment]
You can't import that you have to import what you exported. If you have something that form you can change it to be in the right form.

Remove the "", at the beginning, and put it into the export data as it should be. For example,

{"command":"/tellraw @a %s","jobject":[{"text":"Hello!"}],"jtemplate":"tellraw"}
