### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by sralse** [ezfe/tellraw#175]
Please enter steps to reproduce the issue below, as well as any other information you want to include
Hover events shows "invalid item" instead of the item itself.
I don't think it's a 'Creator' bug but minecraft bug... Any tips or changement of the code could help.
Don't know what's wrong :/

 Provided Data - Do not modify below this line

```
[{"text":"Show entity","hoverEvent":{"action":"show_item","value":"344"}}]
```

**Comment by ezfe** [comment]
Do something like {id:344}, I think
