### ISSUE TITLE
Commands and resetting problems

### ISSUE THREAD

**Issue by KungFuNami** [ezfe/tellraw#178]
I went back to my previous json book which i deleted and i had to reset it. It then wouldn't let me create commands for the text i tried to add (which didn't actually add), and wouldn't create a new page either.

**Comment by ezfe** [comment]
Is this something you can cause to happen again, or was it a one-time thing.

**Comment by KungFuNami** [comment]
I don't know i'll try again, sorry for not answering i was out with family.

**Comment by ezfe** [comment]
It's alright. I ask because when I change formats sometimes things break that wouldn't break otherwise. If you can't get it to happen again then I won't investigate because its likely a one-time issue that I can't easily fix.

**Comment by KungFuNami** [comment]
okay wasn't as bad this time, everything worked and the only thing that was
a little off was the book i last deleted showed up as the command output
but i clicked on delete everything and it was just fine
