### ISSUE TITLE
JSON creator for minecraft

### ISSUE THREAD

**Issue by SeppeLK** [ezfe/tellraw#180]
With JSON creator for minecraft you are able to make signs with colored text on it. I tried it and realised that it worked but you can only type text on the first line of the sign. If you type to much text it doesn't continue on the second line but it stops there.  You can only type text on the first line.
What can I do?

**Comment by ezfe** [comment]
You need to add a new sign line. There should be a button for this.

**Comment by SeppeLK** [comment]
THX!
