### ISSUE TITLE
Issue Report - Output Issue (Other) - Events not working

### ISSUE THREAD

**Issue by TechnoCreeper2** [ezfe/tellraw#181]
Please enter steps to reproduce the issue below, as well as any other information you want to include

So I have a system where if I press 1, 7, 3, and 8 in that order the text will show up and I can click it to set myself a scoreboard value. But, it is not doing the events. I am in 1.10.2 so if it is a formatting issue please tell me the correct formatting/the correct json in your reply.

Thank you,
    -MrTechno

 Provided Data - Do not modify below this line

```
[{"text":"Execute Order 66","color":"black","bold":true,"italic":true,"clickEvent":{"action":"run_command","value":"/scoreboard players set MrTechno 66 1"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Execute Order 66?","color":"black"}]}}}]
```

**Comment by ezfe** [comment]
It's working here. Does the player have the ability to run commands?

I also recommend not using black for the hover text color.

**Comment by TechnoCreeper2** [comment]
+ezfe I am doing this on a singeplayer world and I have cheats on. Also, only the "Execute" is in bold and italics, any reason why?

**Comment by ezfe** [comment]
Well its in Bold and Italics because those checkmarks are applied.
