### ISSUE TITLE
Issue Report - Output Issue (Other) Save

### ISSUE THREAD

**Issue by GateTurtle** [ezfe/tellraw#186]
I'm not sure if it truly is an issue (if not, my appologies). Saving does not work. At the bottom of the pages says 

>  Open Saves 

> 
as this image: ![photo](https://cloud.githubusercontent.com/assets/10764488/17750268/f6c9aac4-6497-11e6-9ce2-f1c79d85ee6a.png)

and then it just says 

> Saves are being phased out 

> 

Thanks!

**Comment by ezfe** [comment]
I have gotten rid of saves, however that button is there so that you can access your previous saves. You should use the export button and save it in a text file on your computer.

**Comment by GateTurtle** [comment]
Thanks, saddly I erased all of them.
