### ISSUE TITLE
Plz Help Minecraft Book Command Gen Is Not Working!

### ISSUE THREAD

**Issue by FGteeVFan122** [ezfe/tellraw#187]
ok so i as creating a book on the JSON Command creator and i got the command and put it in the command block and all it said was null PLZ HELP!
[untitled](https://cloud.githubusercontent.com/assets/21232034/17981128/4f5723c2-6ad0-11e6-961c-1a6ec7ab663e.png)

**Comment by ezfe** [comment]
Please test this in 1.10.2 with the same command.

**Comment by FGteeVFan122** [comment]
hey it worked thanks 😁
