### ISSUE TITLE
No way to tell all players in a region

### ISSUE THREAD

**Issue by XxTurtleDerpxX** [ezfe/tellraw#189]
Hey, would it be possible to make an option so that you could tell all players in a certain amount of blocks range? I tried adding **"r":"30"** into my tellraw after I got it from the site but it didn't work and said "[@: Invalid json: Unterminated array at line 1 column 6]" twice.

**Comment by XxTurtleDerpxX** [comment]
The command that I tried putting in the command block was: tellraw @a ["r":"30""",{"text":"Race Starting In...","color":"dark_aqua","bold":true,"italic":true,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Don't bother reading this!","color":"green"}]}}}]

**Comment by ezfe** [comment]
That is not the correct syntax. Instead of something like `/tellraw @a %s`, use something like `/tellraw @a[r=30] %s`

**Comment by XxTurtleDerpxX** [comment]
Ahh okay thankyou very much for that. I thought the range had to be in the same block of things after the @a
