### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by AndrewRAN** [ezfe/tellraw#193]
Hello. Your site is not only Tellraw command generator, but you wrote in the title of the site and here (screenshot) that your site is only Telllaw command generator. Change, please.
![screenshot_1](https://cloud.githubusercontent.com/assets/23475741/20352940/faac903a-ac3a-11e6-9602-016107de1780.png)

**Comment by ezfe** [comment]
I'm confused where this is broken?

**Comment by AndrewRAN** [comment]
Here: 
![screenshot_2](https://cloud.githubusercontent.com/assets/23475741/20377045/d50bff50-acad-11e6-953b-aa2663e47811.png)

**Comment by AndrewRAN** [comment]
And in the <title> of the site.

**Comment by ezfe** [comment]
Yes, what should it be?

**Comment by AndrewRAN** [comment]
Hm... Minecraft JSON commands generator... or... Minecraft commands generator or something like that.

**Comment by ezfe** [comment]
This isn't a real problem

**Comment by AndrewRAN** [comment]
But it needs change.
