### ISSUE TITLE
New Titel

### ISSUE THREAD

**Issue by BigisBig** [ezfe/tellraw#195]
Hello dear proamierer of jason generator,
There are now with the 1.11 new titles please
complete them, answer me.

LG BIG
Created with the help of google translator

**Comment by ezfe** [comment]
I am confused what you are trying to say. Can you speak in German?

**Comment by BigisBig** [comment]
Ja, ich bin deutscher, es gibt neue title z.B. die actionstbar zeile 1-3.
Kannst du die ergänzen?

**Comment by BigisBig** [comment]
wie hast du die website erstellt?

**Comment by BigisBig** [comment]
@ezfe habe gean
