### ISSUE TITLE
Actzionsbar

### ISSUE THREAD

**Issue by BigisBig** [ezfe/tellraw#196]

**Comment by BigisBig** [comment]
Es gibt in der actzionsbar 3 zeilen bitte ergänze sie

**Comment by ezfe** [comment]
How is the line specified?

Wie wird die Zeile angegeben?

**Comment by BigisBig** [comment]
mit \n

**Comment by BigisBig** [comment]
/tellraw @p ["",{"text":"1. Reihe \n 2. Reihe","color":"dark_red"}]

**Comment by ezfe** [comment]
Minecraft doesn't support it, I cannot fix it.

Minecraft unterstützt es nicht, ich kann es nicht beheben.
