### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by SMASH8530** [ezfe/tellraw#197]
Please enter steps to reproduce the issue below, as well as any other information you want to include

So my problem is that this command won't work cuz it says Invalid JSON:
I found a link to a site where it tells a problem with it? I', not sure but please try to fix it!
http://gaming.stackexchange.com/questions/233834/why-am-i-getting-an-invalid-json-error-for-my-title-command-in-15w35e
What he said "In the snapshots JSON no longer uses lenient parsing, thus you need to put quotation marks around every string:

/title hacatu title {"text":"test"}"

 Provided Data - Do not modify below this line

```
[{"text":"Welcome to Spleef!","color":"dark_green","bold":true,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Made by: VilladsE","color":"dark_red"}]}}},{"text":" Your objective is to kill the other player with your shovel or shear!","color":"yellow"},{"text":" You can reset whenever you want!","color":"gray","italic":true,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[]}}}]
```

**Comment by ezfe** [comment]
Can you screenshot my program's webpage?

**Comment by SMASH8530** [comment]
![image](https://cloud.githubusercontent.com/assets/19620638/21109424/4f6f3e98-c099-11e6-90e2-656824be1549.png)
![image](https://cloud.githubusercontent.com/assets/19620638/21109428/54d26df6-c099-11e6-8a14-c1f6484b2dc7.png)

**Comment by ezfe** [comment]
Alright, should fix itself

**Comment by SMASH8530** [comment]
What? It still doesn't work. What the hec do you mean?

**Comment by ezfe** [comment]
Please try recreating your command from scratch. Use the Delete All button and then re-make it. Sorry about that. Let me know if it still doesn't work.
