### ISSUE TITLE
Actionsbar

### ISSUE THREAD

**Issue by BigisBig** [ezfe/tellraw#198]
Ich habe schon ein par mal deswegen geschrieben aber ich glaube nun zu weißen wie mann die Zeile angibt (die 1. , 3. aber nicht die 2.) 1. Zeile wie gehabt 3. Zeile /title APlayersName toolbar {%} , ich glaube die 2. Zeile auch irgend wie so: /title APlayersName <mit Tab ergänzbar> {%} warum ich das nicht selbst nachgucke der pc an den ich grade sitze hat keine Grafikkarte heißt minecraft geht nicht.

**Comment by BigisBig** [comment]
mit \n kann man in die nächste Zeile wechseln

**Comment by BigisBig** [comment]
/tellraw @p ["",{"text":"1. Reihe \n 2. Reihe","color":"dark_red"}]

**Comment by ezfe** [comment]
#196
