### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by ww1150** [ezfe/tellraw#200]
Please enter steps to reproduce the issue below, as well as any other information you want to include
WTF? - " /blockdata [x] [y] [z] {Text1:"[\"\",{\"text\":\"Admin Panel: \"},{\"text\":\"Unlock Creative\",\"color\":\"gold\",\"bold\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 210 62 291 minecraft:redstone_block\"}},{\"text\":\" - \",\"color\":\"none\",\"bold\":false},{\"text\":\"Lock Creative\",\"color\":\"green\",\"bold\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 210 62 291 minecraft:air\"}}]"} "

? - "\"

 Provided Data - Do not modify below this

**Comment by ezfe** [comment]
I don't understand the issue.
