### ISSUE TITLE
Issue Report - Translation Issue (zh-TW)

### ISSUE THREAD

**Issue by coco0325** [ezfe/tellraw#201]
Please enter steps to reproduce the issue below, as well as any other information you want to include

 Provided Data - Do not modify below this line

```
[]
```
Book - Add book page not "書本換業" is "書本換頁"

**Comment by ezfe** [comment]
https://github.com/ezfe/tellraw/commit/a6c34bac0f64ea368cc0daa6c636b2d87cda2478
