### ISSUE TITLE
Importing and Exporting

### ISSUE THREAD

**Issue by BossC** [ezfe/tellraw#203]
When importing commands that have multiple spaces in them, ex. `{"command":"/tellraw @p %s","jobject":[{"text":"______Testing"}],"jtemplate":"tellraw"}` , It removes all additional spacing besides the first one. This happens in all forms of generation on the site.

**Comment by BossC** [comment]
For some reason, it's removing the additional spaces on GitHub, so imagine the underscores are spaces.

**Comment by ezfe** [comment]
ok, thanks. Ill take a look

**Comment by ezfe** [comment]
What browser are you using?

**Comment by BossC** [comment]
The latest build of Chrome, on Windows 7.

**Comment by ezfe** [comment]
Hi,

This should be fixed now. Please let me know if it isn't.
