### ISSUE TITLE
Multiple Commands?

### ISSUE THREAD

**Issue by DinoMlkShk** [ezfe/tellraw#205]
When I'm using the book generator I want to use multiple commands at once to clear a few items of different kinds, but not all items. I also want it to work as a trade so they can't not have the items and get the thing anyways. Can someone help?

**Comment by DinoMlkShk** [comment]
Also, I need to use multiple commands because, the thing I'm using is a command that wont give them an item. just a skill

**Comment by ezfe** [comment]
You need to find a way to use a single command that triggers multiple commands. The easiest way to do this with the release of 1.12 (friday) is functions.
