### ISSUE TITLE
My book isn't working ._.

### ISSUE THREAD

**Issue by Willimations** [ezfe/tellraw#207]
Please enter steps to reproduce the issue below, as well as any other information you want to include

I'm using 1.12, and trying to generate a book for my minigame map, but it's not working. My generated book when in game just reads: **Invalid book tag**

 Provided Data - Do not modify below this line

```
[{"text":"This is a test blaf"}]
```

**Comment by ezfe** [comment]
Hi,

I can't reproduce this. Can you show me a command to get a book that creates an invalid book?
