### ISSUE TITLE
Issue Report - Output Issue (Bad Preview)

### ISSUE THREAD

**Issue by Reximian9k** [ezfe/tellraw#209]
_Please enter steps to reproduce the issue below, as well as any other information you want to include_

Basically, if the text component is equal to "<br>", the preview acts as an html line break tag. Just a small issue, reporting it in case you don't mind fixing it.

 _Provided Data - Do not modify below this line_

```
[{"text":"hello "},{"text":"<br>"},{"text":" world"}]
```

**Comment by ezfe** [comment]
Fixed, let me know if it's still an issue

**Comment by Reximian9k** [comment]
Hmm, still appears to be present. I've tested with both adding a new component and editing an existing component to "<br>" and can still reproduce the issue.

**Comment by ezfe** [comment]
Ah, the cache has the old version. Chrome has a "Force Reload" option (shift key as a modifier of regular reload), Safari has "Reload from Origin" (option key).
