### ISSUE TITLE
Site is very laggy when I click on buttons

### ISSUE THREAD

**Issue by It5meSam** [ezfe/tellraw#210]
This happens when I'm using a browser. Usually, takes 10 seconds for the loading assets page. It used to be instantaneous for me but now it's laggy :( Also wehen I click on any other button like edit or delete everything. Maybe there's a problem with the server hosting the site?

**Comment by ezfe** [comment]
Hi,

What browser are you trying this on, and what type of computer do you have.

I have confirmed it is functioning correctly on my end ([see here](https://www.youtube.com/watch?v=wA2GOHneaLE))

**Comment by It5meSam** [comment]
Found out the problem. It was an emoji extension I had which basically turned every emoji (unicode) one into its own. Works very well now!

Thanks 👍
