### ISSUE TITLE
Clicking on the arrows to move the text boxes up and down in the main screen does not do anything

### ISSUE THREAD

**Issue by tintin10q** [ezfe/tellraw#213]

**Comment by ezfe** [comment]
The arrows are drag and drop

**Comment by tintin10q** [comment]
Oh oke, sorry for not noticing


________________________________
Van: Ezekiel Elin <notifications@github.com>
Verzonden: dinsdag 24 oktober 2017 02:22
Aan: ezfe/tellraw
CC: tintin10q; Author
Onderwerp: Re: [ezfe/tellraw] Clicking on the arrows to move the text boxes up and down in the main screen does not do anything (#213)


The arrows are drag and drop
