### ISSUE TITLE
Issue Report - Output Issue (Bad Preview)

### ISSUE THREAD

**Issue by leumasme** [ezfe/tellraw#216]
Please enter steps to reproduce the issue below, as well as any other information you want to include

Use \n in book generator. This would create a new line in the book in minecraft, but your generator shows it as \<br>.
This really messes up the preview if you use \n all the time like me.

 Provided Data - Do not modify below this line

```
[{"text":"[","color":"green"},{"text":"Master Book","color":"aqua","bold":true},{"text":"]\\n","color":"green"},{"text":"\\n[PlayerPvP On]\\n","color":"aqua","clickEvent":{"action":"run_command","value":"/scoreboard teams option players friendlyfire true"}},{"text":"[PlayerPvP Off]","color":"aqua","clickEvent":{"action":"run_command","value":"/scoreboard teams option players friendlyfire false"}}]
```

**Comment by ezfe** [comment]
Thanks, this is fixed
