### ISSUE TITLE
Cant sort text parts in tellraw

### ISSUE THREAD

**Issue by leumasme** [ezfe/tellraw#218]
When i try to move / sort text parts in the tellraw generator (click / drag the up / down arrows) nothing happens.

Exported command
```{"command":"/tellraw @p %s","jobject":[{"text":"Items werden Repariert in","color":"gold"},{"text":"5","color":"red"}],"jtemplate":"tellraw"}```

**Comment by ezfe** [comment]
You should be able to drag the arrows up and down (not clicking, click and drag). Does the snot work?

What browser are you using.

**Comment by leumasme** [comment]
"Does the snot work?" typo? or wat is a snod
im using Chrome Version 62.0.3202.75 (Official Build) (64-Bit)
I disabled confirm deletion and enabled structured output in the settings.
maybe im just doin something wrong .-.
Vid-> https://streamable.com/s/yqzxb/hfeiqb

**Comment by ezfe** [comment]
Yes, that was a typo. Thanks for the video, looks like something is broken. I'll check this out.

**Comment by leumasme** [comment]
I dont want to be rude, but are you actually gonna do this some time or is this just gonna stay on ur todo list for 2 years?

**Comment by ezfe** [comment]
@leumasme Hey, sorry about this. Try it now.

**Comment by leumasme** [comment]
yep, thx :3

**Comment by leumasme** [comment]
btw i think this issue was also what #220 was about
