### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by CommandDices** [ezfe/tellraw#219]
Hi,
we'd really like to support you with mining .. but 100% CPU usage is too much ... cant do anything while minig is turned on.
Please fix it so we can support your work :D 

Thanks,
CommandDices

**Comment by ezfe** [comment]
Hi,

Please reject Mining requests, sorry about that. I will investigate when I have time.

**Comment by ezfe** [comment]
Hi, I've disabled mining until I can figure out a better way to do this.

**Comment by CommandDices** [comment]
did you find a better way ?
we'd really like to support with this your site is really helpful

maybe around 20 to 60 % CPU usage ?

if you cannot figure out how much you use maby it's possible to make a Less
an a more mining button so the user can control how much cpu to use

Am 30.11.2017 01:47 schrieb "Ezekiel Elin" <notifications@github.com>:

Closed #219 <https://github.com/ezfe/tellraw/issues/219>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ezfe/tellraw/issues/219#event-1364720163>, or mute the
thread

**Comment by ezfe** [comment]
Hi, yes I understand what you're saying. If you'd like to support me I do have a Paypal, however do not feel obligated.

https://www.paypal.me/ezfe

**Comment by CommandDices** [comment]
Do you use discord ?

I'll talk about paypal with my brother
i think your generator is worth a little donation :)


Am 30.11.2017 21:39 schrieb "Ezekiel Elin" <notifications@github.com>:

**Comment by ezfe** [comment]
Yes, you can find me on Discord: ezfe#5301
