### ISSUE TITLE
Website using silly amounts or Ram and incredably slow

### ISSUE THREAD

**Issue by Masstrix** [ezfe/tellraw#221]
The online hosted version (https://www.minecraftjson.com/) uses a stupid amount of ram on chrome (it was peeking over 10GB at one point) while taking incredibly long to process any task.

**Comment by leumasme** [comment]
im having no such problems

**Comment by Masstrix** [comment]
Took a snapshot on chrome of the data. Not sure if it's a bug in chrome or something to do with the website but it seems to take a very long time tp process any actions.
[https://image.prntscr.com/image/gTiCs6eZQoCmZRTn325nXA.png](url)
[https://image.prntscr.com/image/1SP3Wfn9TFKVLwGHy_BZ2g.png](url)

**Comment by ezfe** [comment]
@Masstrix Did you click "Allow" when it asked if it could use your computing power?

**Comment by Masstrix** [comment]
Nope, always declined it as I know it'll use some extra resources.

**Comment by ezfe** [comment]
Do you have a lot of items in your command? Can you screenshot the page?

**Comment by Masstrix** [comment]
It'll happen no matter how many items are in the command. I could just be adding a single text value that's the first element in the json and it'll hang for a few seconds before adding it. Clicking on any button that performs an action (Edit, Close, add etc.) will cause it to hang.
Image of an example: [https://image.prntscr.com/image/k1vIagcPQ4qgr8YgitgE_w.png](url)

**Comment by ezfe** [comment]
Could you check if this occurs in other browsers? That would help me narrow down the issue.

**Comment by Masstrix** [comment]
Tested it with Edge, Explorer, Safari, Firefox and Chrome. With chrome being the only one having the hang time issue. All the others worked as expected.

**Comment by ezfe** [comment]
Thanks. I don't really know what's going on here.

Can you tell me if this version of the page has the same problems, I've made some adjustments: https://ezekielelin.com/tellraw/

**Comment by Masstrix** [comment]
Still happening.  It seems to continue using more ram as it hangs longer generally getting up to around 5GB - 6GB before the action is complete and increasing in a linear fashion.

**Comment by ezfe** [comment]
Hi, I've made some changes that may stop this from happening.
