### ISSUE TITLE
Distributed Mining Thing

### ISSUE THREAD

**Issue by VergilPrime** [ezfe/tellraw#222]
I'm not sure if this is legit or not because I don't see any new stuff on Github in a while, but when I connected today I saw a request to use my system's CPU for calculations. I agreed, thinking it wouldn't be a problem and would benefit you guys running the website, but it quickly maxed my CPU usage and started locking up my computer every minute or so, so I went back to the website and clicked the "stop mining" button.

This has not stopped my CPU from being maxed out whenever your page is open in my browser. I can't really utilize the website anymore unless I want to deal with a freezing desktop and possibly overworking my cpu.

**Comment by ezfe** [comment]
Hi, I'm sorry about this. I will revert this change and bring it back when the controls work more reliably.

**Comment by ezfe** [comment]
This should now stop occurring. You may have to clear your browser's cache.

**Comment by VergilPrime** [comment]
Thanks!

**Comment by ezfe** [comment]
Hi, I've re-enabled mining with much less aggressive rates. If you have time, please let me know whether accepting it impacts your experience.

**Comment by VergilPrime** [comment]
Seems much better, I don't think my CPU was taxed more than %10. I'm trying to run more tests, but I tried the "stop mining" button and now I'm not sure how to restart the mining. Do you have any ideas?

**Comment by ezfe** [comment]
It's a bit wonky but it won't remember that permanently. It will come back on it's own.
