### ISSUE TITLE
Issue Report - Output Issue (Bad Preview)

### ISSUE THREAD

**Issue by HyperBlueCore** [ezfe/tellraw#224]
Please enter steps to reproduce the issue below, as well as any other information you want to include
the book is in one line only

 Provided Data - Do not modify below this line

```
[{"text":"Let's get you set up with your nickname! "}]
```

**Comment by ThizThizzyDizzy** [comment]
There are a few issues with the preview
Most notable is the lack of wrapping text. Text in the same section will not wrap, although separate sections will (page 3 in preview)
Also, the text and text wrapping is not quite right size, especially with bold text: (page 1)
(text preview)
![Capture](https://user-images.githubusercontent.com/22590237/56815258-dd1ce500-680e-11e9-8c76-e9c4a9f337dd.PNG)
(actual text ingame)
![Capture2](https://user-images.githubusercontent.com/22590237/56815264-e017d580-680e-11e9-836f-14d22b72bb60.PNG)

Exported command:
{"command":"/give @p written_book{pages:%s,title:CustomBook,author:Player}","jobject":[{"text":"       Abilities\\n","bold":true},{"text":"Shield","color":"blue","bold":true},{"text":"        "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaShield set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaShield set 0"}},{"text":"\\n"},{"text":"Black Hole","bold":true},{"text":" "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaBlackHole set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaBlackHole set 0"}},{"text":"\\n"},{"text":"Blast","color":"red","bold":true},{"text":"         "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaBlast set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaBlast set 0"}},{"text":"\\n"},{"text":"Jetpack","color":"yellow","bold":true},{"text":"     "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaJetpack set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaJetpack set 0"}},{"text":"\\n"},{"text":"Channeling","color":"aqua","bold":true},{"text":"   "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaChannel set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaChannel set 0"}},{"text":"\\n"},{"text":"Scanner","color":"green","bold":true},{"text":"    "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaScanner set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaScanner set 0"}},{"text":"\\n\\n\\n\\n\\n\\n\\n"},{"text":"Leech","color":"dark_red","bold":true},{"text":"        "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaLeech set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaLeech set 0"}},{"NEW_ITERATE_FLAG":true},{"text":" Table of Contents\\n","bold":true},{"text":"Mana","color":"dark_purple","bold":true,"clickEvent":{"action":"change_page","value":"3"}},{"text":"........................................3\\n "},{"text":"Abilities","color":"light_purple","bold":true},{"NEW_ITERATE_FLAG":true},{"text":"        Mana","color":"dark_purple","bold":true},{"text":"\\n   Mana is a powerful form of energy capable of manipulating the building blocks of the universe. It can be manually controlled, or used by machines.\\n\\n\\n\\n\\n          "},{"text":"[Back]","color":"red","clickEvent":{"action":"change_page","value":"2"}}],"jtemplate":"book"}

**Comment by ezfe** [comment]
I've cleaned up the previews so they should be better, but they're not perfect.
