### ISSUE TITLE
String? What?

### ISSUE THREAD

**Issue by Moonlightdrop** [ezfe/tellraw#225]
I don’t  t get you mean by insert a “string “ it didn’t give me anything when I exported

**Comment by ezfe** [comment]
Hi, a string is programming lingo for any quantity of text. When you press export, it will reveal the text that you can copy and paste somewhere else for safekeeping and re-import in the future. The text highlighted in this image is the "string" which one would paste into the import field.

<img width="580" alt="screen shot 2018-01-23 at 9 37 55 pm" src="https://user-images.githubusercontent.com/1449259/35311669-afc7ef24-0085-11e8-8a09-899bccdd01e8.png">
