### ISSUE TITLE
Sorting parts in Book editor does not work (again)

### ISSUE THREAD

**Issue by leumasme** [ezfe/tellraw#230]
Hey, had this issue a while ago and you fixed it, aaand broke it again.
Sorting Text parts in book 1.8 editor does not work. Yes i am dragging and not clicking.

**Comment by ezfe** [comment]
What browser are you using?

**Comment by leumasme** [comment]
65.0.3325.181 (offcicial build) (64-Bit) (cohort: Stable)

**Comment by leumasme** [comment]
oo

**Comment by ezfe** [comment]
Can you try again? You may have to force reload

https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Google_Chrome

**Comment by leumasme** [comment]
Yup, works!
