### ISSUE TITLE
SSL privacy error on translate.minecraftjson.com

### ISSUE THREAD

**Issue by bemoty** [ezfe/tellraw#232]
It seems like the SSL certificate for [translate.minecraftjson.com](https://translate.minecraftjson.com) (actually *.oneskyapp.com) doesn't have a SAN entry for translate.minecraftjson.com and thus is invalid. Since the website uses HSTS, this makes the translation page inaccessible.

My suggestion would be to set all links to redirect the user directly to the OneSky project page instead of using a custom sub-domain.

```
User agent: Google Chrome version 66.0.3359.81 (Official Build) beta (64-bit)
OS: Windows 10 (Version 10.0.16299.334)
```

**Comment by ezfe** [comment]
Ah, thanks. I forgot about this page. I will take care of this.

**Comment by ezfe** [comment]
Looks like I cannot login to OneSky at all. I have removed the link to this page in the meantime.
