### ISSUE TITLE
[Book] Hover text should be allowed to be edited or imported in some way.

### ISSUE THREAD

**Issue by 123111qwerty** [ezfe/tellraw#234]
Currently, having to reformat everything from scratch is a huge bummer, this project is one of the best tellraw generators out there, but lacks a lot of support for importing and exporting files.

Implementing a system similar to CrushedPixel's json editor would be neat.

**Comment by ezfe** [comment]
Unfortunately the project is not modular enough to make it easy to do. I have a side project restructuring the backend of this to be more flexible and modular but it's slow as I'm busy with other work.

I am well aware of the hover text problems.

**Comment by ezfe** [comment]
I've implemented full hover text editing
