### ISSUE TITLE
Wrong text on command block

### ISSUE THREAD

**Issue by ThomasGHacc** [ezfe/tellraw#235]
I have been making a server and I needed a title command block, I used generators, typed it on my own, consulted guides, and I still can’t resolve it. So what happens is, when I put the command on the command block and I put a pressure plate over it, the actual command: `/title @a title %s”,”jobject”:[{“text”:”Welcome to the server”,”color”:”gold”,”bold”:true,”italic”:true,”underlined”:true}],”jtemplate”:”title”}`  the text doesn’t work, it doesn’t say “Welcome to the server but it says, [“,”color”:”gold”,”bold”:true,”italic”:]

Can someone help me with this text issue on the command block, I will keep searching for answers as this goes.

**Comment by ezfe** [comment]
Alrighty, so I'm not sure what you've been doing but if you see `jobject` or `jtemplate` anywhere you're working with the result of the [Export] button, which is intended only for re-importing back onto the website.

Could you screenshot the website?

**Comment by ThomasGHacc** [comment]
By the way, I am doing this on an IOS Apple IPad Pro
![b0d95809-6bc2-486e-a7a5-66656ab2d9dc](https://user-images.githubusercontent.com/40694157/42096107-b9aafe1e-7bb4-11e8-9cfb-1a5b68afdcfa.png)

I imported the string of the command and now Im here. (this is my 2nd time using a command block in mc) where’s the import?
