### ISSUE TITLE
no built in option to add a new line

### ISSUE THREAD

**Issue by Widdlemombles** [ezfe/tellraw#238]
i noticed that the new and old book generators didn't have an option to create a new line, so i tried to add a line by adding some text that said "\n" (without the quotations). this temporary solution that i came up with seems to be quite glitchy and unreliable therefore a built in option would be much more reliable.

**Comment by ezfe** [comment]
That’s the supported way to do it, what issues have you run in to other than it being a hidden feature?

**Comment by Widdlemombles** [comment]
it will sometimes remove text and make me start over.

**Comment by ezfe** [comment]
@Widdlemombles That's an issue with your browser that I cannot control. You can always export the text and save it in a text editor or the like.

**Comment by Widdlemombles** [comment]
thanks for the help.
