### ISSUE TITLE
Data Merge Block Support

### ISSUE THREAD

**Issue by Lawsmat** [ezfe/tellraw#243]
Hi! This isn't really an issue, but is sort of a feature request... 1.13 doesn't have blockdata support, so you should add /data merge block too (don't remove blockdata though, because 1.12 people might still use the generator).

**Comment by ezfe** [comment]
Sounds good, thanks for letting me know. I may not get around to this for a while but I'll add it to the list.

**Comment by ezfe** [comment]
@Lawsmat Could you verify the expected format for the command? If you go on minecraftjson.com and start with the `blockdata` one, edit the "Player and command" field until it looks like you would expect a `data merge` command to look like. If you give that to me here I can add it quickly.

**Comment by ThizThizzyDizzy** [comment]
/data merge block [x] [y] [z] {%s}

**Comment by ezfe** [comment]
Should be all set
