### ISSUE TITLE
Massive Lag when editing large commands

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ezfe/tellraw#250]
I'm making  large book with plenty of formatting. I'm only on ~20 pages, but I get massive amounts of lag when editing lines.
If I type enough at a time, the website will "Aw, Snap!" (Google Chrome)

Can you add an option to disable automatic updating of the output? (and add a manual update button)

Exported command:
{"command":"/give @p written_book{pages:%s,title:\"Thizzy'z Guide to Mana\",author:ThizThizzyDizzy}","jobject":[{"text":"       Abilities\\n","bold":true},{"text":"Shield","color":"blue","bold":true,"clickEvent":{"action":"change_page","value":"10"}},{"text":"        "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaShield set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaShield set 0"}},{"text":"\\n"},{"text":"Black Hole","bold":true,"clickEvent":{"action":"change_page","value":"11"}},{"text":" "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaBlackHole set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaBlackHole set 0"}},{"text":"\\n"},{"text":"Blast","color":"red","bold":true,"clickEvent":{"action":"change_page","value":"12"}},{"text":"         "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaBlast set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaBlast set 0"}},{"text":"\\n"},{"text":"Jetpack","color":"yellow","bold":true,"clickEvent":{"action":"change_page","value":"13"}},{"text":"     "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaJetpack set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaJetpack set 0"}},{"text":"\\n"},{"text":"Channeling","color":"aqua","bold":true,"clickEvent":{"action":"change_page","value":"14"}},{"text":" "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaChannel set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaChannel set 0"}},{"text":"\\n"},{"text":"Scanner","color":"green","bold":true,"clickEvent":{"action":"change_page","value":"17"}},{"text":"    "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaScanner set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaScanner set 0"}},{"text":"\\n\\n\\n\\n\\n\\n\\n"},{"text":"Leech","color":"dark_red","bold":true},{"text":"        "},{"text":"[ON]","color":"dark_green","clickEvent":{"action":"run_command","value":"/trigger manaLeech set 1"}},{"text":"[OFF]","color":"dark_red","clickEvent":{"action":"run_command","value":"/trigger manaLeech set 0"}},{"NEW_ITERATE_FLAG":true},{"text":" Table of Contents\\n","bold":true},{"text":"Mana","color":"dark_purple","bold":true,"clickEvent":{"action":"change_page","value":"3"}},{"text":"........................................3\\n "},{"text":"Abilities","color":"light_purple","bold":true,"clickEvent":{"action":"change_page","value":"5"}},{"text":".............................5\\n "},{"text":"Machines","color":"light_purple","bold":true},{"text":"..........................?\\n"},{"NEW_ITERATE_FLAG":true},{"text":"        Mana","color":"dark_purple","bold":true},{"text":"\\n   Mana is a powerful form of energy capable of manipulating the building blocks of the universe. It can be stored by players or in gems, and can be manually controlled or used by machines.\\n\\nPlayers can discover mana by drinking"},{"NEW_ITERATE_FLAG":true},{"text":"Mana potions","color":"light_purple","underlined":true},{"text":". Before it is completed, players will slowly loose progress in mana discovery. Once completed, players can store and use mana.\\nPlayers can hold 1,000,000 mana, and regenerate 20 per second. Mana is used for "},{"text":"Abilities","color":"light_purple","underlined":true,"clickEvent":{"action":"change_page","value":"5"}},{"text":" and "},{"text":"Machines","color":"light_purple","underlined":true},{"text":"."},{"NEW_ITERATE_FLAG":true},{"text":"When a player's mana reaches full, they will gain 10 hearts of health boost. These will disappear only if the player falls below full mana."},{"NEW_ITERATE_FLAG":true},{"text":"       Abilities\\n","color":"black","bold":true},{"text":"Players have many Abilities that require mana. Most abilities require discovery. To discover an ability, you must have enough mana for discovery, and try to use the ability.\\nThe ","color":"black"},{"text":"Totem","color":"green","underlined":true},{"text":" ability is automatic, does not require discovery, and cannot be disabled.","color":"black"},{"NEW_ITERATE_FLAG":true},{"text":"disabled.\\nSome abilities give the player ","color":"black"},{"text":"Warp","color":"dark_purple","underlined":true},{"text":" when used, or even when enabled.\\n\\nAbilities can be toggled with the following command or with the ","color":"black"},{"text":"Control Panel","color":"black","underlined":true,"clickEvent":{"action":"change_page","value":"1"}},{"text":" at the beginning of this book.\\n","color":"black"},{"text":"/trigger <abilityID>","color":"dark_gray"},{"NEW_ITERATE_FLAG":true},{"text":"For an unknown reason, many abilities are more powerful in the nether.","color":"black"},{"NEW_ITERATE_FLAG":true},{"text":"       Ability List\\n","color":"black"},{"text":"Shield","color":"blue","bold":true,"clickEvent":{"action":"change_page","value":"10"}},{"text":".................................10\\n","color":"black"},{"text":"Black Hole","color":"black","bold":true,"clickEvent":{"action":"change_page","value":"11"}},{"text":"....................11\\n","color":"black"},{"text":"Blast","color":"red","bold":true,"clickEvent":{"action":"change_page","value":"12"}},{"text":"....................................12\\n","color":"black"},{"text":"Jetpack","color":"yellow","bold":true,"clickEvent":{"action":"change_page","value":"13"}},{"text":"............................13\\n","color":"black"},{"text":"Channeling","color":"aqua","bold":true,"clickEvent":{"action":"change_page","value":"14"}},{"text":"...................14\\n","color":"black"},{"text":"Scanner","color":"green","bold":true,"clickEvent":{"action":"change_page","value":"17"}},{"text":"..........................17\\n\\n","color":"black"},{"text":"Totem","color":"green","bold":true},{"text":"..................................18\\n\\n\\n\\n\\n","color":"black"},{"text":"Leech","color":"dark_red","bold":true},{"text":"....................................0\\n","color":"black"},{"NEW_ITERATE_FLAG":true},{"text":"        Shield\\n","color":"blue","bold":true},{"text":"Creates a mana shield around the player, shielding from incoming damage.\\n","color":"black"},{"text":"Activated by Sneaking\\n","color":"gray","italic":true},{"text":"Minimum mana: 100\\nUsage: 2000/sec\\nDiscovery: 100,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Rain","color":"blue"},{"text":"\\nWhen active, the mana shield will provide the player with 10 "},{"text":"(20)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" hearts of absorption."},{"NEW_ITERATE_FLAG":true},{"text":"      Black Hole","bold":true},{"text":"\\nPulls nearby items towards you.\\n"},{"text":"Passive\\n","color":"gray","italic":true},{"text":"Minimum mana: 75\\nUsage: 1500/sec/item\\nDiscovery: 150,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Smoke","color":"black"},{"text":"\\nWhen activated, any items within 10 blocks of the player will move towards the player at 5 "},{"text":"(7.5)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" meters per second."},{"NEW_ITERATE_FLAG":true},{"text":"        Blast\\n","color":"red","bold":true},{"text":"Damages entities around the player.\\n"},{"text":"Activated by sneaking and looking down\\n","color":"gray","italic":true},{"text":"Minimum mana: 25,000\\nUsage: 25,000\\nDiscovery: 200,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Fire","color":"yellow"},{"text":"\\nWhen activated, any entities within 10 blocks will take 6 "},{"text":"(18)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" hearts of damage."},{"NEW_ITERATE_FLAG":true},{"text":"      Jetpack\\n","color":"yellow","bold":true},{"text":"Launches the player into the sky\\n"},{"text":"Activated by sneaking while in the air\\n","color":"gray","italic":true},{"text":"Minimum mana: 250\\nUsage: 5000/sec\\nDiscovery: 250,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Fire","color":"yellow"},{"text":"\\nWhen activated, the player will fly upwards at 22.5 "},{"text":"(31.5)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"meters per second."},{"NEW_ITERATE_FLAG":true},{"text":"    Channeling\\n","color":"aqua","bold":true},{"text":"Strikes the player with lightning\\n"},{"text":"Activated by sneaking and looking up\\n","color":"gray","italic":true},{"text":"Minimum mana: 200,000\\nUsage: 200,000\\nDiscovery: 600,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Fire","color":"yellow"},{"text":"\\nWhen activated, lightning will strike the player, the blocks the player was standing on will be smelted, and"},{"NEW_ITERATE_FLAG":true},{"text":"the energy from the lightning will give the player the following effects:\\n"},{"text":"- Full food"},{"text":"\\n- Heal 4 "},{"text":"(8)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Hearts"},{"text":"\\n- 1s Invulnerability, Glowing, and Invisiblity"},{"text":"\\n- 5s "},{"text":"(8s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Fire Resistance"},{"text":"\\n- 10s "},{"text":"(15s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" of 4 "},{"text":"(6)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Absorption hearts"},{"text":"\\n- 10s "},{"text":"(15s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Strength II "},{"text":"(III)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"NEW_ITERATE_FLAG":true},{"text":"- 2s "},{"text":"(3s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Water Breathing"},{"text":"\\n- 25s "},{"text":"(35s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Speed II "},{"text":"(III)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"\\n- 25s "},{"text":"(35s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Haste II "},{"text":"(III)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"\\n- 15s "},{"text":"(20s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Night Vision"},{"text":"\\n- 15s "},{"text":"(20s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":" Jump Boost II "},{"text":"(III)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"\\n- 10s "},{"text":"(15s)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"\\nRegeneration II "},{"text":"(III)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"NEW_ITERATE_FLAG":true},{"text":"      Scanner\\n","color":"green","bold":true},{"text":"Scans for nearby ores\\n"},{"text":"Passive\\n","color":"gray","italic":true},{"text":"Minimum mana: 250,000\\nUsage: 5400 ","color":"dark_purple"},{"text":"(2,000)","color":"red","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Nether","color":"red"}]}}},{"text":"/sec\\nDiscovery: 800,000","color":"dark_purple"},{"text":"\\nParticles: "},{"text":"Totem","color":"green"},{"text":"\\nWhen activated, any ores within 3 blocks of the player will be highlighted."},{"NEW_ITERATE_FLAG":true},{"text":"        Totem\\n","color":"green","bold":true},{"text":"Passive\\n","color":"gray","italic":true},{"text":"Minimum mana: 50,000\\nUsage: 50,000","color":"dark_purple"},{"text":"\\nWhen a totem of undying is used, the player will levitate into the air for a few seconds, then hit the cround, gaining invulnerability and regeneration 5 for 5 seconds. If the player was in water or lava, a protective barrier will be created around them"}],"jtemplate":"book"}

**Comment by ezfe** [comment]
So the reason this happens is because the entire book is re-generated every time you type. I may be able to make a hidden setting for you that makes it faster and

**Comment by ezfe** [comment]
So since I'm actually in the process of rewriting the entire site, I won't be addressing this issue right now. I encourage to make your books in chunks and put them together in a text editor.

I will try to make sure my new version does not have this problem.

**Comment by ezfe** [comment]
So my new version handles this better, but it's still laggy when typing on the main page. If you open up a snippet and edit, it's super fast, and there's no additional notable lag. You can check it out right now at preview.minecraftjson.net (keep in mind it's not finished!)

**Comment by ezfe** [comment]
Alrighty, so I've checked and it's not laggy editing this command anymore. Please let me know if you're still having issues.
