### ISSUE TITLE
does not work in 1.13 ranged

### ISSUE THREAD

**Issue by leefromvt** [ezfe/tellraw#253]
cannot seem to ad "distance=25" it stops code from working in 1.13.2 the base code does seem to work though.
/tellraw @p ["",{"text":"This is test text","color":"dark_purple"}]  --works
/tellraw @p[distance=25] ["",{"text":"This is test text","color":"dark_purple"}]  --dontwork

**Comment by ezfe** [comment]
That's because you're using `distance` wrong, it should be `@p[distance=..25]`, what you're doing gives selects players exactly 25 blocks away, not up to 25 blocks away.
