### ISSUE TITLE
Broken Hover Text

### ISSUE THREAD

**Issue by Beaupedia** [ezfe/tellraw#262]
Trying to make the hover just say "/warp SAS"

Screenshots:
https://i.imgur.com/qiH3sjb.png
https://i.imgur.com/LeUzCjh.png

The hover appears to be broken, here's the export I get:

{"jformat":5,"jobject":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"afdec304-f773-4ad8-9d8f-daeb6427f616","text":"\n"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"13","insertion":"","click_event_type":"2","click_event_value":"/warp SAS","hover_event_type":"1","hover_event_value":"","hover_event_children":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"da1ccecc-c07d-486d-bece-2b37b2b0d389","text":"/warp SAS"}],"id":"b623f15e-32e5-4c64-9619-f280921d936c","text":"It's time for Staff Appreciation! Stop by /warp SAS to leave notes and gifts for the staff who work hard to keep this community running - then be ready to party at 7PM ET on October 5th for our Staff Appreciation Spectacular! We've got lots of contests and prizes lined up for you!"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":16,"insertion":"","click_event_type":0,"click_event_value":"","hover_event_type":0,"hover_event_value":"","hover_event_children":[],"id":"ba3506e6-9fe0-491b-8dde-8ec3f5d21fc2","text":"\n"}],"command":"/tellraw @p %s","jtemplate":"tellraw"}

**Comment by ezfe** [comment]
This should be fixed now
