### ISSUE TITLE
Entity NBTs & interface/useage suggestion

### ISSUE THREAD

**Issue by RoarkCats** [ezfe/tellraw#263]
Currently, you only have the option to use NBT storage while NBT entity is also a thing but not listed. Another thing, personally, I think that when you hold the button to quick-add text or what not, it shouldn't close the menu so you can click say 10 times without having to re-open the menu each time, also it would be nice if you could do this for duplicating too.

**Comment by ezfe** [comment]
Do you have a reference for the NBT Entity? I'm happy to take a look at that.

And thanks for the suggestion on quick-adding and duplicating, I'll take a look at making that possible.

**Comment by RoarkCats** [comment]
> Do you have a reference for the NBT Entity? I'm happy to take a look at that.

https://www.youtube.com/watch?v=xo-ksI9V6Yk

**Comment by ezfe** [comment]
Should be mostly done, except for the "interpret" option

**Comment by ezfe** [comment]
I've added an interpret option
