### ISSUE TITLE
Book give command not working for 1.12.2

### ISSUE THREAD

**Issue by CoasterFan5** [ezfe/tellraw#266]
Minecraft version 1.12.2
date: October 22 2019
Os: Windows 10
Browser: Google Crome

When you copy the give command for a book, it will not give it to you, and it requires some editing of the command. 
This is the command that was generated:
/give @p written_book{pages:["[\"\",{\"text\":\"Are you a citizen of The United States of America?\",\"color\":\"red\"},{\"text\":\"\\n\"},{\"text\":\"Yes I am!\",\"color\":\"black\"}]"],title:"Custom Book",author:Player}
However, in order to use the command, you must add 1 0 and a space after writen book:
/give @p written_book 1 0 {pages:["[\"\",{\"text\":\"Are you a citizen of The United States of America?\",\"color\":\"red\"},{\"text\":\"\\n\"},{\"text\":\"Yes I am!\",\"color\":\"black\"}]"],title:"Custom Book",author:Player}
This is not a priority, but would be nice to have!

**Comment by ezfe** [comment]
Hi @CoasterFan5, is it not sufficient that the command "remembers" itself and is editable on the site? I'd prefer not to have to support old version of the game individually since there are so many variations but I might be able to find a way to solve your issue.
