### ISSUE TITLE
import string issue

### ISSUE THREAD

**Issue by AvelgamerYT** [ezfe/tellraw#268]
Hi,

The website you made (the newer version) will **absolutely not** accept my string. It would be super helpful to fix this so I can continue generating text for my server.

Please fix ASAP!
![websiteissueohno](https://user-images.githubusercontent.com/59103028/71299346-96a66880-2352-11ea-83b6-8a56d1224793.PNG)

**Comment by ezfe** [comment]
Can you either email it to me (contact form is on the website) or comment with your input string here so I can take a look?

**Comment by AvelgamerYT** [comment]
Hey Ezekiel,

I forgot to take down the post; I was accidentally typing in the command
where the string was supposed to be, LOL! Please forgive me for any trouble
or confusion my post may have caused.

Thanks,
Zach

**Comment by ezfe** [comment]
No worries!
