### ISSUE TITLE
Sign 1.8

### ISSUE THREAD

**Issue by DevLucas14** [ezfe/tellraw#269]
Hello dear developer,
I, DevLucas, love to work with commands and would be happy if the character generator in version 1.8 is available again.
Because I don't like to work in 1.13.
PS:
We, the users, are very lucky that there is such a simple website.

L. G.
Lucas // DevLucas

**Comment by ezfe** [comment]
Hi Lucas,

Does this command work in 1.8:

```
/give @p sign 1 0 {BlockEntityTag:{Text1:"[\"\",{\"text\":\"Test \\\"1.8\\\" Sign\",\"bold\":true,\"underlined\":true,\"color\":\"gold\"}]",id:"Sign"}}
```

**Comment by DevLucas14** [comment]
Okay, thanks!

**Comment by ezfe** [comment]
What I meant was that you can write `/give @p sign 1 0 {BlockEntityTag:{%s,id:"Sign"}}` in the command line at the top of the page to get the 1.8 signs
