### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by Pablowills** [ezfe/tellraw#272]
I tried to import **/tellraw @a ["",{"text":"Hola ~~ quieres"},{"text":" Barrier","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s barrer 64"}},{"text":" Bloque de comandos","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s command_block 64"}},{"text":" Bloque de comandos en cadena","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s chain_command_block 64"}},{"text":" Bloque de comandos de repetición","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s repeating_command_block 64"}},{"text":" Bloque estructural","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s structure_block"}},{"text":" Vagon de bloque de comandos","color":"gold","bold":true,"clickEvent":{"action":"run_command","value":"/give @s command_block_minecart"}}** but there says 

>![image](https://user-images.githubusercontent.com/51543996/75824536-ab9b7100-5d71-11ea-9270-8b4220e7539b.png)

**Comment by ezfe** [comment]
Hi Pablowills,

You can only import what you've previously exported from the site. It cannot read the command that you would put in Minecraft, unfortunately.
