### ISSUE TITLE
Click Event doesn't show up anymore

### ISSUE THREAD

**Issue by NightTerror04** [ezfe/tellraw#282]
I saw that they updated the website and I really like the new color thing but it also got rid of the click event option which I was going to use

**Comment by ezfe** [comment]
Hi @NightTerror04,

The click event option is still there for me? Could you clarify whether it looks like this for you:

<img width="1104" alt="Screen Shot 2020-07-19 at 10 24 17 AM" src="https://user-images.githubusercontent.com/1449259/87877044-0264b880-c9aa-11ea-87eb-2716495216f3.png">
