### ISSUE TITLE
https://minecraftjson.com/ Problem

### ISSUE THREAD

**Issue by Michal-1312** [ezfe/tellraw#283]
Basically The Book and Sign and Screen Overlay Doesn't Work at All. But Good News I Love The Tellraw Generator Because Thats The Only Thing That Works.

Please Fix It ASAP! I have a project what im working on for over a YEAR. It Needs To Be Done By 2020-08-12

Going On Holiday on 2020-08-13 So Please Fix it.

-Michal

**Comment by NightTerror04** [comment]
The sign and Screen overlay worked for me the other day when I used them

**Comment by ezfe** [comment]
@Michal-1312 What version of Minecraft are you using? Could you upload a screenshot of the website?

**Comment by Michal-1312** [comment]
> 
> 
> @Michal-1312 What version of Minecraft are you using? Could you upload a screenshot of the website?

I am using 1.16. and i also put the Version into 1.16

I Tried doing everything again and it all Works. When i posted this Problem It didn't Work, But Thank You Anyways for The Help :)

**Comment by ezfe** [comment]
Glad you've figured it out!

**Comment by Michal-1312** [comment]
> 
> 
> Glad you've figured it out!

Thank You :smile:
