### ISSUE TITLE
This was a command that I got from the tallraw generator, I exported it, and it worked great. However when I imported the same command to be able to add to it, it said that there was a problem importing it.

### ISSUE THREAD

**Issue by KingBoo14325** [ezfe/tellraw#285]
/give @p written_book{pages:["[\"\",{\"text\":\"Click one to give every player a kit, then choose a map.                              \"},{\"text\":\"Slime             \",\"bold\":true,\"color\":\"green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 304 redstone_block\"},\"hoverEvent\":{\"action\":\"show_text\",\"contents\":[\"\"]}},{\"text\":\"Tank          \",\"bold\":true,\"color\":\"dark_gray\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 303 redstone_block\"}},{\"text\":\"Fireman           \",\"bold\":true,\"color\":\"gold\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 302 redstone_block\"}},{\"text\":\"Speedy             \",\"bold\":true,\"color\":\"aqua\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 301 redstone_block\"}},{\"text\":\"Bow Master     \",\"bold\":true,\"color\":\"red\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 300 redstone_block\"}},{\"text\":\"Sword Master       \",\"bold\":true,\"color\":\"green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 299 redstone_block\"}},{\"text\":\"Ender          \",\"bold\":true,\"color\":\"dark_aqua\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 298 redstone_block\"}},{\"text\":\"Potion Master      \",\"bold\":true,\"color\":\"dark_purple\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 297 redstone_block\"}},{\"text\":\"Troller       \",\"bold\":true,\"color\":\"dark_green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/setblock 281 53 296 redstone_block\"}}]"],title:"Kit Selector",author:James}

**Comment by ezfe** [comment]
@KingBoo14325 Unfortunately it’s very hard for me to import from the Minecraft commands-there’s an export button that goes to a format I specify which is easier to re-import. Sorry about this!
