### ISSUE TITLE
["", is unnecessarily at the start of all commands

### ISSUE THREAD

**Issue by T0RNATO** [ezfe/tellraw#286]
The command `/tellraw @p ["",{"text":"hi","color":"gold"}]` could just be written as `/tellraw @p {"text":"hi","color":"gold"}` without the square brackets.

When the square brackets are necessary, as in `/tellraw @p ["",{"text":"hi","color":"gold"},{"text":"hello","bold":true}]` the `"",` at the start is unnecessary, and could just be `/tellraw @p [{"text":"hi","color":"gold"},{"text":"hello","bold":true}]`

**Comment by ezfe** [comment]
It's unnecessary in some commands, like the one you just gave, **but it's necessary in many commands**. I'll consider removing it in the one's where it's unnecessary.

**Comment by T0RNATO** [comment]
Yes, but even in commands which require square brackets, like one of the ones I gave, there is an unecessary `"",` at the start of the square brackets.

`/tellraw @p [**"",**{"text":"hi","color":"gold"},{"text":"hello","bold":true}]`

**Comment by ezfe** [comment]
It actually is necessary. Without it, some stuff doesn't work. Observe the difference in this command when you remove it:

`/tellraw @p ["",{"text":"Text1","underlined":true},{"text":"Text2"}]`
