### ISSUE TITLE
Inserting a newline character into a text field escapes the newline

### ISSUE THREAD

**Issue by Kalikars** [ezfe/tellraw#288]
Attempting to type a newline character `\n` into any text field automatically escapes the character in the command line, leading to the text field using the literal characters \n instead of a new line.

Suggesting to add functionality to not auto escape certain characters.

EDIT: Upon further inspection, the LineBreak functionality works as a suitable workaround. Closing the issue.

**Comment by ezfe** [comment]
Hi @Kalikars , I see you've figured out the issue. I added the line break option since (as you've observed) `\n` is escaped. In the past, I had custom logic to not escape \n, but that gets complicated fast and led to a bunch of other random problems which is why I made it a special button.
