### ISSUE TITLE
The master branch doesn't include a built site

### ISSUE THREAD

**Issue by 66Leo66** [ezfe/tellraw#292]
The `Download Website` button on the website menu links to the archive of master branch, which doesn't include a built site.
Please consider setting up `Github Actions` to build (or maybe creating a release) automaticly.

**Comment by ezfe** [comment]
Thanks for reminding me, in the past the site was pre-compiled and I forgot about this when moving it over.

**Comment by ezfe** [comment]
@66Leo66 I believe I've corrected this issue - there should be a built artifact on releases now
