### ISSUE TITLE
HoverEvent (ShowItem)

### ISSUE THREAD

**Issue by DerJulHD** [ezfe/tellraw#300]
HoverItem does not work. The generator shows: {"text":"_[ANY TEXT]_", "hoverEvent":{"action": "show_item", "**value**":"_[ANY ITEM]_"}}. But it should be: {"text":"_[ANY TEXT]_", "hoverEvent":{"action": "show_item", "**contents**":"_[ANY ITEM]_"}}. Instead of "**value**" it should be "**contents**".

**Comment by ezfe** [comment]
Looks like this was changed in 1.16, I'll tie it in with the version selector

**Comment by ezfe** [comment]
All sorted - the hover text was being correctly set but the hover items and entities were not.
