### ISSUE TITLE
Import a book

### ISSUE THREAD

**Issue by BlackDragon05** [ezfe/tellraw#301]
Import a book in 1.16+ doesn't work, for any type, i literally tried to copy the code it gave me and pasted it into import and it gives me an error
![image](https://user-images.githubusercontent.com/44489133/109390107-f06bd080-790f-11eb-8f6c-01673bb028a0.png)

**Comment by ezfe** [comment]
Unfortunately I can't parse out the command I give, I can only parse the one resulting from clicking Export
