### ISSUE TITLE
When one presses "Add Text" and then "Selector," making a Selector with visible text is seemingly impossible.

### ISSUE THREAD

**Issue by CommandoEchino** [ezfe/tellraw#303]
I tried to add a selector with visible text to a book I was working on but it didn't work.

Here's what I put into the generator:

![image](https://user-images.githubusercontent.com/64720141/111568488-3aa9da00-8777-11eb-837f-59c5bc979c02.png)

Here's what I put into the formatting options:

![image](https://user-images.githubusercontent.com/64720141/111568537-5319f480-8777-11eb-88b9-e97007d2fd4c.png)

Here's what it shows as in the preview pane:

![image](https://user-images.githubusercontent.com/64720141/111568330-f0285d80-8776-11eb-8fdf-597e9196f0c0.png)

and here's what it actually rendered as in-game:

<img src="https://user-images.githubusercontent.com/64720141/111568269-d2f38f00-8776-11eb-885f-892214873ddb.png" width="400">

Here is the command that the generator outputted. As you can see, it doesn't actually add the `"text":"blah blah blah","` to the part of the command that concerns the selection:

`/give @p written_book{pages:["[\"\",{\"text\":\"The History of Echino's Minecraft Server\",\"bold\":true,\"color\":\"#1C50AC\"},{\"text\":\"\\n\"},{\"text\":\"\\n\"},{\"text\":\"The seed of this server is \"},{\"selector\":\"903159579731182\",\"bold\":true,\"color\":\"light_purple\",\"clickEvent\":{\"action\":\"copy_to_clipboard\",\"value\":\"903159579731182\"}},{\"text\":\"The server initially ran on the vanilla jar, until late 2020 when it was transitioned over to Paper.\"}]"],title:"Custom Book",author:Player}`

EDIT: In order to actually make a selector with visible text, you just have to press "Add Text" and then "Text" instead of "Selector" like I did previously...which makes no sense -- I mean, how else are you supposed to use a selector if the text that's supposed to be clicked on is invisible??

**Comment by CommandoEchino** [comment]
Okay, it's actually not impossible, you just have to press "Add Text" and then "Text" instead of "Selector" like I did previously...which makes no sense. I'm leaving the issue open as I assume this was not an intentional feature and is some sort of bug -- I mean, how else are you supposed to use a selector if the text that's supposed to be clicked on is invisible??

**Comment by ezfe** [comment]
I'm sorry for the confusion - selectors are for getting the result of entity selectors, like `@p`, etc. What are you trying to achieve here?

If you want it to be clickable, do regular text and choose a click action.

**Comment by CommandoEchino** [comment]
> I'm sorry for the confusion - selectors are for getting the result of entity selectors, like `@p`, etc. What are you trying to achieve here?
> 
> If you want it to be clickable, do regular text and choose a click action.

I just wanted clickable text.

So just to be clear, is the selector for getting like, the name of the nearest player with `@e`, and then displaying that? I'm kinda confused and curious about what it does, I'd love to learn more.

But yeah, it should really be more clear what that button does on the site. : /

**Comment by ezfe** [comment]
Yup - it's named after the field in Minecraft but I can definitely improve the labels for things!
