### ISSUE TITLE
Execute command needs updating

### ISSUE THREAD

**Issue by doinkythederp** [ezfe/tellraw#305]
In 1.16 the execute command syntax has changed:
- Old: `execute <who> <x> <y> <z> <command>`

- New: `execute as <who> run <command>`

I'm hoping this can be reflected on your generator's Basic Tellraw -> `execute` template.
Thanks!

**Comment by ezfe** [comment]
I've updated the command list to ... Minecraft 1.15, by mistake ... but it includes the change you mentioned since apparently I had an even older one loaded in.
