### ISSUE TITLE
It seems I can't make new pages.

### ISSUE THREAD

**Issue by GormGormly** [ezfe/tellraw#315]
There is no way to add pages to a book. The "previous" and next" buttons are greyed out but indicate you should be able to flip through the pages, but there is no way to add pages. I'm having a hard time believing that this is something you don't know about so I think I'm just missing something that is not obvious. I'm just lost because your code also doesn't validate in VSC (contradictory use of single vs double quotes) but also when I try to change your code to what I get from a /data get in minecraft VSC also won't validate that so I'd rather just have your generator output the final book without having to change anything in VSC... so I need to know how to add extra pages on your site.

**Comment by GormGormly** [comment]
Sorry I looked in the add text but missed pages. I have some sort of karma that lets me only figure out things after I ask for help.  Please remove this from the internet.

**Comment by ezfe** [comment]
I'll delete this 🙂
