### ISSUE TITLE
Can not see the command to copy and paste

### ISSUE THREAD

**Issue by Eatham532** [ezfe/tellraw#317]
![image](https://user-images.githubusercontent.com/78714349/129703307-7ff2c477-52e9-4c9a-a044-a4473505a35b.png)

This is all I see. There is information there though. Please fix

**Comment by Eatham532** [comment]
Update: 
Clicked the sign button and then went back. This did fix it. But just so you know this does happen sometimes so make sure to see if you can patch it before other people get it as well.

p.s. Love the website

**Comment by ezfe** [comment]
Hi @Eatham532 - thanks for letting me know. Could you click export (even if it's not happening anymore) and drop it here so I can take a look? You can add it as a comment here.
