### ISSUE TITLE
Line break not working with CustomName

### ISSUE THREAD

**Issue by tvhee-dev** [ezfe/tellraw#322]
/summon armor_stand ~ ~ ~ {Invisible:1b,Invulnerable:1b,NoGravity:1b,CustomName:'["",{"text":"Test","color":"yellow"},"\n",{"text":"Line 2","color":"dark_red"}]',CustomNameVisible:1b} does not work if I add the \n linebreak. I am using Paper 1.17.1.

**Comment by ezfe** [comment]
I don't believe you can do this, unfortunately:

https://gaming.stackexchange.com/a/385912/105673

**Comment by tvhee-dev** [comment]
Ok it indeed works if you summon one 0.3 under the first one, thanks!

**Comment by ezfe** [comment]
Happy to help!
