### ISSUE TITLE
"Cannot parse as JSON"

### ISSUE THREAD

**Issue by s3902298** [ezfe/tellraw#325]
This message shows up when I try to set the hover event to anything other than "Show text"

**Comment by ezfe** [comment]
@s3902298

You need to assign it to valid JSON. If you think you're already doing this, please comment what you're entering.

You can read more here https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Java_Edition at `hoverEvent > contents`. It should be JSON (`{"key": "string" }`) and match one of the intended formats.

I'd like to make an actual UI for entering these in the future, but that's not available at the moment.
