### ISSUE TITLE
An error occurred importing my command

### ISSUE THREAD

**Issue by SadeSito** [ezfe/tellraw#338]
I can't import my command because of an unknown error. I wish you can deal with it. Waiting for your answer.
![sth wrong](https://user-images.githubusercontent.com/109900820/180643829-263812de-5259-4250-8240-b4d6d7caa251.png)

**Comment by ezfe** [comment]
You cannot import the Minecraft commands. You must use the export button first.

The Minecraft commands are complex and difficult to reliably import.
