### ISSUE TITLE
when typing a \ it puts two

### ISSUE THREAD

**Issue by FuzzyL16** [ezfe/tellraw#340]
when putting a text of a \ it will put two \\

**Comment by ezfe** [comment]
Does it show as two in-game?

**Comment by FuzzyL16** [comment]
It will have two in the output yes, and when I’m doing Unicode I’d doesn’t work 

example I put on websites 
\E000

output
\\E000

Doesn’t matter if there’s any other text just the backslash seams to duplicate it self

this sucks because when I get in game and run it it doesn’t show anything because it’s \\E000

**Comment by ezfe** [comment]
I updated your comment - use the tickmark (below the tilde on american keyboards) instead of a quote.

**Comment by ezfe** [comment]
That being said, this is #293. The truth is that I don't have that much time in my life to work on this project beyond keeping it functional. If I ever do have time to work on new features this is definitely on my list.

Is it possible to embed the characters directly? For example, this: ``? That should avoid this. Alternatively, you can do a find and replace for `\\E000` to `\E000` before saving it in game. Most text editors can do this easily.
