### ISSUE TITLE
[Suggestion] On export, don't export default settings/blank settings (would help make the message smaller)

### ISSUE THREAD

**Issue by RandomGgames** [ezfe/tellraw#342]
When exporting a message for safe keeping, especially when the message has many parts, the export is VERY LARGE. This seems due to every aspect that would be able to be added also being exported, even if they default to blank/false.

For example, just the command which only used one text box 
```mcfunction
/tellraw @p "Hi"
```
exports to
```json
{"jformat":8,"jobject":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"font":null,"color":"none","insertion":"","click_event_type":"none","click_event_value":"","hover_event_type":"none","hover_event_value":"","hover_event_object":{},"hover_event_children":[],"text":"Hi"}],"command":"/tellraw @p %s","jtemplate":"tellraw"}
```
 which seems just completely unnecessary.

**Comment by ezfe** [comment]
I'm working on importing Minecraft commands, which will remove this as an issue since you can just save that (see #339)
