### ISSUE TITLE
List not showing.

### ISSUE THREAD

**Issue by F6347** [ezfe/tellraw#346]
No list in translation
![image](https://user-images.githubusercontent.com/103911667/221898765-6beebdbe-b220-4bb3-a546-582d41ef652b.png)

**Comment by ezfe** [comment]
I haven't loaded the 1.19 config in yet, I'll do that asap. In the mean time, if you change the version to 1.18 you'll get most of them

**Comment by F6347** [comment]
Thanks!

**Comment by ezfe** [comment]
Should be all set please let me know if I broke anything
