### ISSUE TITLE
Incorrect preview for alternate font

### ISSUE THREAD

**Issue by Jaddub-commits** [ezfe/tellraw#347]
Their is two fonts in the vanilla game files -- "minecraft:default" and "minecraft:alt", the alternate font is used for the enchantment table.

When you use the alternate font in game it appears like in the image. But on the text preview on the website the font does not change.
![image](https://user-images.githubusercontent.com/80666883/226218582-102d898e-c1b0-465a-b3ab-07aabbadcca9.png)

Example: _/tellraw @p ["",{"text":"Normal Font","font":"minecraft:default"},"\n",{"text":"Alternate Font","font":"minecraft:alt"},""]_

**Comment by ezfe** [comment]
Unfortunately I have not implemented any form of font rendering in the preview
