### ISSUE TITLE
Sign option doesnt work (Essentials)

### ISSUE THREAD

**Issue by Error336070** [ezfe/tellraw#352]
This is probably because of the essentials plugin we have installed. but the sign option basically doesnt work and says unknown item name or something like that
just was wondering if it would be possible to add a version that works on essentials. we can use the /data command to edit signs that already exist so maybe you can add that as a workaround
I've tested the /data command and it does work on essentials

using google chrome and Windows 10 Pro

**Comment by ezfe** [comment]
The sign option isn’t working in 1.20 and I’m pushing up a note about that now while I investigate. Thank you

**Comment by ezfe** [comment]
Signs have been fixed in 1.20. Please let me know if you're still experiencing any problems.

You can write your own commands in the command field if you need to make small tweaks.
