### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by minhhoangharry** [ezfe/tellraw#353]
i tried with book but it not work

**Comment by ezfe** [comment]
Can you provide a screenshot or more details on how it's not working. What mincraft version.

**Comment by minhhoangharry** [comment]
> Can you provide a screenshot or more details on how it's not working. What mincraft version.

1.19

**Comment by ezfe** [comment]
I just started up 1.19 and created a book without issue. Can you either "Export" your command and paste it here or screenshot what you're entering?
