### ISSUE TITLE
cant import tellraw with  scoreboard objective

### ISSUE THREAD

**Issue by lunarwolf2008** [ezfe/tellraw#357]
importing tellraw commands with a scoreboard objective gives failed to parse tellraw in place of the scoreboard objective

![image](https://github.com/ezfe/tellraw/assets/141184225/7d704265-d2b9-4941-be10-656eb487742b)

command: `/tellraw @p ["",{"text":"current quest: Chop 10 oak logs Progress:"},{"score":{"name":"*","objective":"wood"}},{"text":"/10"}]`

notes: the same result is achieved with a target selector or a name  in place of *

**Comment by ezfe** [comment]
Should be all set, may take a few minutes to appear
