### ISSUE TITLE
Tellraw clickable text not working

### ISSUE THREAD

**Issue by ViktorBacke** [ezfe/tellraw#360]
While testing my tellraws I had no issues with clickable text strings but when my players that are not OP on my server tried, it didn't work. I know it's not related to the tool itself and more just the command but if you could help that would be much appreciated.

**Comment by ezfe** [comment]
They won't be able to run protected commands just because they are in a tellraw, you'll have to create a trigger, and use the trigger command to execute it. It should allow them to do that.

**Comment by ezfe** [comment]
https://minecraft.wiki/w/Commands/trigger

**Comment by ViktorBacke** [comment]
Thanks a lot, appreciate it!
