### ISSUE TITLE
External Links lead to Fandom Wiki instead of Updated Minecraft Wiki 

### ISSUE THREAD

**Issue by ZmaZes** [ezfe/tellraw#361]
Specifically in the translation page, the "Read More" link points to https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Translated_Text even though it should point to https://minecraft.wiki/w/Raw_JSON_text_format#Translated_Text for more updated information.
I'm using chrome but that shouldn't change anything.
![image](https://github.com/ezfe/tellraw/assets/116696525/2b9f2596-db1f-48ac-8c16-b1b452cf0d5c)

**Comment by ezfe** [comment]
The link has been updated. You may need to clear your browser's cache to see the new link.
