### ISSUE TITLE
Can't build and run this Project.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [ezfe/tellraw#362]
Hello!
I'm experiencing some errors when trying run this Project.

Logs are here: https://pastebin.com/WFwT3gZR

**Comment by ezfe** [comment]
It seems the instructions are wrong, you can use `nom run preview` instead, which should work

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> nom run preview

If You meant "npm" by "nom", then it's working.
