### ISSUE TITLE
Book and Sign command not working for version newer versions (1.20.5-1.21+)

### ISSUE THREAD

**Issue by Gadgetman1** [ezfe/tellraw#364]
Recently Mojang has updated their systems for commands and it's broken the give commands for the sign and the book features.

Book 1.20
```
/give @p written_book{pages:["{\"text\":\"Hello\",\"color\":\"dark_red\"}"],title:"Custom Book",author:Player}
```
Sign 1.21
```
/give @p written_book[written_book_content={pages:["{\"text\":\"Hello\",\"color\":\"dark_red\"}"],title:"Custom Book",author:Player}]
```

Sign 1.20
```
/give @p oak_sign{BlockEntityTag:{Text1:"\"Hello\""}}
```
Sign 1.21
```
/give @a oak_sign[block_entity_data={id:oak_sign,front_text:{messages:['["",{"text":"hello","color":"dark_red"}]','[""]','[""]','[""]']}}]
```

Changing the book should be easy, you just got to add the part saying "[written_book_content=]" around the NBT, but the signs got changed a lot. This was tested on 1.21, but I believe it affects 1.20.5/.6 also.

**Comment by ezfe** [comment]
These changes have been fixed with updated command templates. These templates are not connected to the Minecraft version selected, so you will have to re-select "book" or sign" to get the new templates.
