### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by starshine123705** [ezfe/tellraw#367]
Please enter steps to reproduce the issue below, as well as any other information you want to include

We can use the format like {'[{"text":"text"}]'} to avoid that many \ inside,and it caused that I cant use \n to change to another line

 Provided Data - Do not modify below this line

```
[{"text":"","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/trigger Trigger set 1"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":""}]}}}]
```

**Comment by starshine123705** [comment]
/give @p written_book{pages:["[\"\",{\"text\":\"aaa\",\"color\":\"aqua\",\"bold\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/trigger Trigger set 1\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"to aaa\"}]}}}]"],title:CustomBook,author:Player}

**Comment by starshine123705** [comment]
/give @p written_book{pages:["[\"\",{\"text\":\"靶场\",\"color\":\"aqua\",\"bold\":true,\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/trigger Trigger set 1\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\"传送到靶场\"}]}}}]"],title:CustomBook,author:Player}
It all act like this,both legacy and the newest version

**Comment by starshine123705** [comment]
![QQ20240817-235353](https://github.com/user-attachments/assets/756b306e-5efb-46eb-917a-32675bc42461)

it all act like this

**Comment by starshine123705** [comment]
It supposed to be this kind,which acts better than current one.
/give @p written_book{pages:['[{"text":"\\n","bold":true,"color":"aqua","clickEvent":{"action":"run_command","value":"/trigger Trigger set 1"}},{"text":"","bold":true,"color":"red","clickEvent":{"action":"run_command","value":"/trigger Trigger set 2"}}]'],filterd_title:"",title:"",author:""}

**Comment by ezfe** [comment]
1. You can use the "Line Break" option to change to a new line.

<img width="690" alt="Screenshot 2024-08-17 at 1 03 43 PM" src="https://github.com/user-attachments/assets/369c321b-f400-42e7-a32b-38c192126afa">

2. Using single quotes does allow me to use fewer `\"` however I would then have to do `\'` manually which is not easy.
