### ISSUE TITLE
books not working with 1.19

### ISSUE THREAD

**Issue by Meuh332** [ezfe/tellraw#377]
(sorry for bad english, I'm am French)
 Hi, I love your tool but I found an issue, in 1.19 (idk for other versions) books give are not with:
/give @p written_book[written_book_content={pages:[pages],title:"text",author:Player}]
 but with:
 /give @p written_book{pages:[pages],title:"text",author:Player}
 
 Hope you a good day 🙃

**Comment by ezfe** [comment]
See my comment on #374
