### ISSUE TITLE
Don't automatically give @a

### ISSUE THREAD

**Issue by julianwachholz** [ezfe/tellraw#67]
Just use `@p` that's way more sensible please.

**Comment by metarmask** [comment]
:+1: But only for books and (/give) signs

**Comment by ezfe** [comment]
Guys...there's a reason it's a text field.

**Comment by julianwachholz** [comment]
A textfield that auto selects all text when clicking into it doesn't help a lot. This is not how you approach  Github issues, @ezfe.

**Comment by metarmask** [comment]
Are you talking about the command tempate textfield? It doesn't auto select all text for me...

Then how do you approach them?

I can't think of many situations where I would want to give a sign item with custom NBT to all players on a server...
Yes... it's only one character... I can change it. But sometimes I forget to do it, and accidentally give all players on my server a book that gives them blocks they shouldn't have access to.

**Comment by ezfe** [comment]
ok, I can change it. and @julianwachholz , I don't know what your talking about regarding it selecting everything.
