### ISSUE TITLE
Issue Report - Output Issue (Other)

### ISSUE THREAD

**Issue by Theredstonevoid** [ezfe/tellraw#86]
Please enter steps to reproduce the issue below, as well as any other information you want to include

 Provided Data - Do not modify below this line

```
[{"text":"Hello i am dodeihfe","color":"gray","bold":"true","italic":"true","underlined":"true"}]
```
The /give sign isnt working

**Comment by Theredstonevoid** [comment]
it just gives me a sign

**Comment by ezfe** [comment]
Yes, what happens when you place the sign on the ground?

**Comment by Theredstonevoid** [comment]
nothing is on it it just makes me type something

**Comment by Theredstonevoid** [comment]
like a normal sign

**Comment by ezfe** [comment]
Strange. Can I see the command it gives you?

**Comment by Theredstonevoid** [comment]
/give @a sign 1 0 {BlockEntityTag:{Text1:"{\"text\":\"\",\"extra\":[{\"text\":\"Hello\",\"color\":\"gray\",\"italic\":\"true\",\"underlined\":\"true\"}]}",id:"Sign"}}

**Comment by Theredstonevoid** [comment]
dont worry it works now
