### ISSUE TITLE
Can't open saves

### ISSUE THREAD

**Issue by metarmask** [ezfe/tellraw#94]
The saves button doesn't open the saves.

The console gives me two errors:
Object.keys called on non-object in tellraw.js at 1399
Cannot read property 'jobject' of null at 1322

Browser: Chrome
OS: Windows 7

**Comment by metarmask** [comment]
Just noticed more non-functional buttons:
* Report an Issue
* Light/Dark theme
* Fix escaping issue

**Comment by ezfe** [comment]
Yeah, I screwed something up and I'm not sure what. I need to poke around a bit.

**Comment by ezfe** [comment]
Seems like the issue was the code crashing for some reason. I fixed the offending line (which has been unchanged for who knows how long).
