### ISSUE TITLE
'Delete all saves' just deleting every second save

### ISSUE THREAD

**Issue by metarmask** [ezfe/tellraw#97]
The 'delete all saves' button only deletes every second save starting from the first.
If I create 6 saves only 1, 3, 5 gets deleted.
But creating 5 saves deletes only 1 and 3.

Browser: Chrome OS: Windows 7

**Comment by ezfe** [comment]
Oh that's strange. ok I'll take a look.

**Comment by ezfe** [comment]
I can't reproduce this. I made 4 saves and it deleted all of them. Do I need to make more?

**Comment by metarmask** [comment]
For me it works with any amount. Just tested it with internet explorer, behaves exactly the same as in chrome.

**Comment by metarmask** [comment]
Got exactly the same result with:
Chrome OS - Chrome
Android - Default samsung browser
Android - Chrome
But with Android - Firefox it first deleted 3 of 4, then the second time I tried it with 4 saves it deleted them all.

**Comment by ezfe** [comment]
Hmm ok, thanks

**Comment by metarmask** [comment]
I think I know why this happens. When the code deletes a key from the storage, the positioning changes.

**Comment by metarmask** [comment]
i = 13
13: save 1 -deletes-
14. save 2
15. save 3
16. save 4

i = 14
13. save 2
14. save 3 -deletes-
15. save 4

i = 15
13. save 2
14. save 4
15. randomData -deletes-

**Comment by metarmask** [comment]
That fixed it!
